### ISSUE TITLE
Feature request: ability to make quantity and unit cost visible

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#100]
Would it be possible to make the quantity of stock held and unit cost information that is in the .yaml file display on the ticker app? It could just be an option like the other display options where you add the --show flag into the config file.

**Comment by dtcooper** [comment]
As well as day gains per quantity, not just total gains! ❤️

**Comment by viperperidot** [comment]
@achannarasappa looking forward to 3.1.0, looks like it will be a big release!! :D

**Comment by viperperidot** [comment]
Would it also be possible to be able to show your initial investment cost for each lot? (Didn't think I needed to create a new issue for this)

**Comment by achannarasappa** [comment]
Added in release v3.1.0
