### ISSUE TITLE
Feature request: Self update

### ISSUE THREAD

**Issue by mouuff** [achannarasappa/ticker#102]
**Problem Statement**
I am currently working on a easy to setup updater, which could be used for ticker.
The project is named rocket-update, it is hosted here: https://github.com/mouuff/go-rocket-update
Currently the project is in development stage, and we are looking for projects like yours, to use our solution, and get feedbacks from your community and your team.

If you are interested in this project, it is entirely possible for me to implement it.

**Proposed Solution**
The updates could be triggered automatically or manually, it would directly find the binaries using github release.
It is possible to verify that is installation is good and rollback if its not the case. The project also have security features such as RSA signing.

This is much easier than asking users to download a zip, unzip to a folder, create shortcut themselves, and do the process over and over again each update.

Understand that we are not asking you to use this project tomorrow.
I have opened this issue to talk with you and see if you are open to such projects.

Thank you

**Comment by mouuff** [comment]
I m adding this here, since this thread is related: https://github.com/achannarasappa/ticker/discussions/72

**Comment by achannarasappa** [comment]
Thanks for the suggestion @mouuff

How does this compare to existing libraries such as https://github.com/sanbornm/go-selfupdate?

In general, I see auto-updating as providing a marginal amount of convenience to users given there are suitable alternatives by means of package managers.

**Comment by mouuff** [comment]
Hello!

The library that you linked (go-selfupdate) requires you to run a server by yourself while rocket-update allows you to use github releases (as well as your own server if you need/want).

Here is a small list of the features of rocket-update which go-selfupdate doesn't have:
- Rollback (which allows installation verification)
- RSA signing
- Multiple sources for updates

And this is just the beginning, I plan to add even more features in the near future.

I think it would be pretty convenient for the users, since they wouldn't even notice that it is being updated.

Using a solution such as rocket-update would work for any platform. Ticker doesn't have a package for windows or OSX, right ?

For now, here is what I propose: I can implement a way to call rocket-update for ticker using an argument (something like `-self-update`) so you can test for yourself and have a better of how it would look like.

Thank you
