### ISSUE TITLE
Feature request: market cap and volume data available?

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#109]
I am not sure if this data is available through Yahoos API or not but would it be possible to add the Market Cap and Volume data to show when the --fundamentals flag is on? If this data is not available through the API that you use then we can just close this issue, just an idea that would give even more information on screen.

**Comment by viperperidot** [comment]
I think another metric that would be useful to have if possible would be the 52 week high/low.

**Comment by achannarasappa** [comment]
Added in the latest release
