### ISSUE TITLE
Cannot find config file

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#11]
The config file is not in the default directly as mentioned here and I do not see it anywhere.

**Comment by 097115** [comment]
You should create one, `.ticker.yaml` in  your `$HOME` directory.

**Comment by viperperidot** [comment]
Oh ok thanks I didn't know I needed to do that myself, maybe just update the instructions so it is more clear.

Thanks

**Comment by Bleighhhh** [comment]
hi! I have the .ticker.yaml file in my home but it is like ticker cannot detect it. How do I tell ticker to use that config file? thanks
