### ISSUE TITLE
Day change and total change not currently working

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#110]
Ok I think this is the last thing that might have stopped working after adding some of the new features like currency conversion.

The day change and total change that are shown at the top of Ticker are not currently working for me. I have currency conversion turned on so maybe that is why. For example the total change is showing my portfolio being in the positive but it is actually in the negative. 

The day change is really not making sense but I think both may be due to enabling the currency conversion like found in #107.

Maybe just have a look at the formula used for these fields and make sure there is no double conversion happening again, if you need more info I can give more.

**Comment by achannarasappa** [comment]
Good catch! Looks like the original cost basis for each lot was not being converted. I've fixed in the latest release v3.1.2

**Comment by viperperidot** [comment]
Ok awesome the total change looks good now, the only thing that looks incorrect to me now is the day change. Maybe it is just wrong because markets are closed right now? Not sure but it shows an increase of an amount larger than the value of my portfolio which is impossible and also even though it shows that number the % only says an increase of 3.25%. So something is definitely wrong with this field as well...

Any ideas what is going on with this field?

**Comment by achannarasappa** [comment]
Ah another bug - in this case, the total cost value was being used as the day change. Should be fixed with v3.1.3

**Comment by viperperidot** [comment]
Yep fixed with 3.1.3 thanks!
