### ISSUE TITLE
Feature request: Ability to set the unit cost for lots in local currency

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#111]
Can we make it possible to use the local currency that you have selected for your currency conversion to be used as the base unit cost for your lots with no conversion?

The reason for this is that if you put your unit cost in the .yaml as USD for an exchange and then use the currency conversion to display the unit cost and for your profit/loss calculation then the number will be incorrect relative to what you actually paid at the time you purchased your shares.

For example if you bought shares for X amount then that is the real number you want used for your profit/loss calc and to be shown as your unit cost in Ticker. But if you have your unit cost converted then the exchange rate will be different from when you originally purchased the shares and therefore show an incorrect profit/loss and unit cost relative to what you paid using the exchange rate on the date of purchase.

Not sure how difficult this would be to implement but basically what I am asking for is that whatever currency you have specified in your .yaml file, that is the currency that you use to enter your unit cost for your lots. That way it will not change due to fluctuation in the exchange rate over time. 

Hopefully this makes sense

**Comment by viperperidot** [comment]
I realized a simpler way of explaining this is that your unit cost should not change, it is fixed at the time of purchase. But by having this number constantly converted using the most recent forex exchange rate this number fluctuates when it should remain static.

**Comment by achannarasappa** [comment]
Thanks for suggesting this. It makes sense to me to include this option in a future release

**Comment by achannarasappa** [comment]
Added in the latest release
