### ISSUE TITLE
Make right-aligning the information optional?

### ISSUE THREAD

**Issue by 097115** [achannarasappa/ticker#113]
**Problem Statement**
After the commit fb09ef118acdc6cc24ac0d0ed994ec718970f526, all the stock-related information is now right-aligned. Which is not only quite a drastic change in the UI but also simply makes it harder to read since the different data cells are now just too close to one another (notice, there's A LOT more free space on the left now than it used to be -- while there's more data to display)

**Proposed Solution**
Make this right-alignment optional :)

**Comment by cwarden** [comment]
Maybe just revert fb09ef118acdc6cc24ac0d0ed994ec718970f526.  I also found it much easier to readh price/value/change on the right, and all supplemental info on the left.

Moving additional data closer to right might work ok in a single-row display with column headers and cell separators.

**Comment by 097115** [comment]
@cwarden That's what I did, indeed (and some other changes, too). However, while maintaining a personal fork is fun, it's certainly doesn't protect you from possible incompatible future changes in the upstream :)

**Comment by achannarasappa** [comment]
Was hoping this would add to clarity but I can see you point where there's now a lot of info on the right side.  I'm planning to re-evaluate the positions of all elements in #121. There's been a lot of information added now as optional rows but I'm thinking this can be better organized and screen real-estate can be better used. If you have ideas or suggestions of how to best position elements in general I'd invite you to add them there.

**Comment by 097115** [comment]
@achannarasappa Thanks for your interest! (not that I can add much, though :)

As @cwarden has pointed out, I reverted fb09ef1 and thus now have essentials on the right and all the supplemental information on the left. I also sort of joined `fundamentals` and `holdings` to be on one line, with `fundamentals` on the left again, and `holdings` on the right. Here's a pic: https://i.imgur.com/SJ7TWy9.png

Sure, with that approach, one's terminal size can't be narrowed down much without sacrificing something but may be that's exactly where these possible future layout options will have their say?

Just my two cents :)

**Comment by achannarasappa** [comment]
In the latest release, additional information is shown in line with positions and quotes but a larger terminal window is needed to make these visible. Hopefully this make it easier to values a littler easier to read. Have a look and let me know what you think - I'll close this issue for now but do re-open if you feel there's more to be improved.
