### ISSUE TITLE
Feature Request: Fees are taking into accounts

### ISSUE THREAD

**Issue by basetta** [achannarasappa/ticker#116]
**Problem Statement**
Fees are not talking into consideration.

**Proposed Solution**
It would be nice if in the lots we can add also the fees.

**Comment by achannarasappa** [comment]
Hey @basetta,

Would you be able to provide a proposal for how this would be represented in the config file and some use cases?

**Comment by achannarasappa** [comment]
Thanks for the details @freznicek . I can see how this would help properly represent the total cost of purchase. I'll schedule it for a future release.

**Comment by achannarasappa** [comment]
Added in the latest release
