### ISSUE TITLE
Feature Request: Export data

### ISSUE THREAD

**Issue by luanmuniz** [achannarasappa/ticker#12]
One of my everyday routines is to update a spreadsheet with the current values of the tickers I have invested.
This system is great for that! Instead of going to a bunch of websites, I just run the terminal and it's done.

An export to JSON feature for example would be great because I could just put a script to run on the cronjob to update my spreadsheet using its data.

Thank you for the app :)

**Comment by achannarasappa** [comment]
Thanks for the suggestion @luanmuniz

Exporting data is outside the scope of what I originally had in mind for `ticker` as a TUI to track live stock prices. If you'd like to export data at a point in time, I'd suggest you have a look the underlying API call e.g.:
`curl "https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&symbols=NET" | jq '.quoteResponse.result[]'`

This can provide you the same information in a machine readable format that you can transform into a CSV or whatever suits your use case best.
