### ISSUE TITLE
Responsive terminal design

### ISSUE THREAD

**Issue by achannarasappa** [achannarasappa/ticker#121]
The current UI is designed to support terminal width from 80 characters without any upper bound. For users with larger terminal, there may be substantial empty and unused space between the left and right blocks of information.

The ideal solution would display more information on wider terminal and and less on smaller terminals. Possible ways to achieve this:

- For fields with labels, hide labels
- For numeric values with changes, hide the change value
- For long text fields, truncate text
- For small terminals, hide fields based on anticipated importance to users

**Comment by viperperidot** [comment]
Just my opinion but I have adjusted my terminal size to fit Ticker ideally, can't everyone do this?

**Comment by achannarasappa** [comment]
@viperperidot that's a fair point and reasonable workaround

One reason I had for this change was to capitalize on the extra space for larger terminal windows and show some of the extra information like fundamentals and holders on the default two lines. This would allow users with larger terminals to see more information in the same vertical space. This would also alter the layout to better support more pieces of information (as suggested in #114, #109) and improve readability (as suggested in #113)

Interested to discuss this further and hear more input and alternatives.

**Comment by viperperidot** [comment]
Ok that makes sense, once you add more features the smaller terminal windows could get a little crowded. But the user also has the ability to disable some of the additional information if they just want a quick snapshot in a small window and use full screen if they want all the details manually. Having it responsive would take a little config out of the equation though which might be nice for some people. Personally I dont find the smaller terminal to be too busy, but I do agree with #113 that currently when you use a full screen there it a lot of blank space in the terminal. That is actually why I found the ideal size to make everything look nice and then made that my default when using ticker.

Awesome to hear that #109 and #114 are going to be implemented, super excited for those additional details. Ticker is really turning into a super useful tool and my main portfolio tracker as I am sure it is for many other stock investors who use Linux.

**Comment by achannarasappa** [comment]
Added in latest version
