### ISSUE TITLE
panic when there's only one currency

### ISSUE THREAD

**Issue by achannarasappa** [achannarasappa/ticker#125]
@achannarasappa do you want a separate issue for this one? https://github.com/achannarasappa/ticker/commit/2f674085#r47140876

_Originally posted by @cwarden in https://github.com/achannarasappa/ticker/issues/112#issuecomment-780157077_

**Comment by achannarasappa** [comment]
Thanks for reporting @cwarden 

Can you provide some more details on how to replicate this bug or a sample config file? I have tried to replicate with no luck

**Comment by cwarden** [comment]
Here's a minimal config file to replicate:
```
watchlist:
  - RDS.B
```

**Comment by achannarasappa** [comment]
Thanks for the example. In this case, the root cause could be because the symbol does not exist in Yahoo finance or the symbol differs. Searching `RDS.B` returns the information for `RDS.BA` in Yahoo finance. Is _Royal Dutch Shell plc (RDS.BA)_ the company you wanted to track?

What's strange is that it return any information at all. In any case, I'll add some handling for the condition where a quote does not have a currency

**Comment by pichalite** [comment]
@cwarden @achannarasappa I had similar issue with "BRK.B". Yahoo has the ticker as "BRK-B". For "RDS.B", use "RDS-B".

**Comment by cwarden** [comment]
Thanks, @achannarasappa and @pichalite.  Yes, it's the Royal Dutch Shell Class B ADR.

**Comment by achannarasappa** [comment]
I've pushed a fix but there's some issue with goreleaser that I'll have to look into before it's available

**Comment by achannarasappa** [comment]
New version has been released - please reopen if you're still experiencing the issue
