### ISSUE TITLE
Add option to change the colors of the various UI elements

### ISSUE THREAD

**Issue by danaspiegel** [achannarasappa/ticker#126]
**Problem Statement**
I have a **white** background on my terminal screen. Yes, black is traditional, but I find a white background easier to read. :) With a white background, the display of information in the UI is mostly unreadable, either being too light (greens, grays) or being inverted gray with lighter gray foreground coloring.

![image](https://user-images.githubusercontent.com/6631/108222430-cabc1b80-7106-11eb-8088-073f8de59b64.png)

**Proposed Solution**
I would like the ability to configure in the ticker.yml colors for both background and foreground of the various elements or of whichever styles are being used, including the background color of the whole UI (I wouldn't mind having a way to make the background black while keeping the default terminal background white).

**Alternatives**
N/A

**Use Cases**
See above

**Additional context**
I use this tool on Mac OS X Terminal.app. I can provide the terminal color configuration if requested.

**Comment by achannarasappa** [comment]
Thanks for the suggestion! I've heard this a couple time and I think it make sense to include at the minimum a light color scheme UI but ideally something that is either dynamic (i.e. detects the background color and adjusts) or configurable (i.e. setting the colors explicitly)

**Comment by viperperidot** [comment]
Not sure what distro OP is using but you should be able to just create a new terminal theme and create a new profile for it. You can leave your default white but switch to the custom ticker profile theme that you created when you run the app.

**Comment by fspoettel** [comment]
I like how tickrs [handles this](https://github.com/tarkah/tickrs/wiki/Config-file). It defaults to system-defined ANSI256 colors and default terminal background/foreground rather than hardcoding hex values. It also supports setting specific hex values via the config file. This approach degrades nicely for light backgrounds and other unusual themes in my testing.

I adjusted ticker on my personal fork [to use ANSI16 colors](https://github.com/fspoettel/ticker/commit/4ed8c864a1d98d91786c1661855bad4ecd9914d6) while keeping support for price gradients by evaluating terminal theme colors via `te.ConvertToRGB()`.
I don't advocate for switching to ANSI16 or any specific theme, just wanted to show an example of what this could look like.

**Comment by danaspiegel** [comment]
> Not sure what distro OP is using but you should be able to just create a new terminal theme and create a new profile for it. You can leave your default white but switch to the custom ticker profile theme that you created when you run the app.

I'm actually on Mac OS using the default Terminal.app. Installation via homebrew. ANSI colors are unchanged from default, but foreground and background colors are inverted (black foreground, white background).

> I like how tickrs handles this.

This sort of solution would work for me as well. Just being able to actually define at least primary colors would solve the issue.

**Comment by achannarasappa** [comment]
In the latest release, I've added better support for non-TrueColor terminals and the ability to set a custom color scheme. Check it out and let me know what you think!

I'll close this issue for now but feel free to re-open or open a new issue if you feel this feature could be further improved

**Comment by danaspiegel** [comment]
First, thanks for the effort in putting in configurable colors. It definitely works (mostly), and generally solves the reason why I originally opened this issue originally.

I believe, however, that there is a bug or two in the use of the colors (or parsing of the colors.

I tried this color scheme:

```
colors:
  text: "#000000"
  text-light: "#333333"
  text-label: "#777777"
  text-line: "#00ffff"
  text-tag: "#545454"
  background-tag: "#ffffff"
```

and while it mostly works, the `text-tag`, `text-line` and possibly another of the colors isn't used. It reverts to the default color, seemingly.

Separately, It would be really useful to be able to set a max value for the red/green quote value colors. I understand that they change brightness depending (on something; not really sure and didn't have a chance to read the code yet). On a white background, the brightest green is mostly unreadable.

LMK if I should open another issue for the color range issue with red/green.

![image](https://user-images.githubusercontent.com/6631/111580270-a303b600-878d-11eb-9cda-711c86475f3f.png)

**Comment by danaspiegel** [comment]
(also, I can't reopen the issue. LMK if you want me to open a new one or if you can re-open)

**Comment by achannarasappa** [comment]
Thanks for feedback and raising the issue with the colors not working. I've tested it and it does seem to be working on my end:
![image](https://user-images.githubusercontent.com/1489983/120250052-cac1d080-c24a-11eb-9f76-e94b4ea03b5e.png)

The color library used supports truecolor but if the terminal does not, it will down sample to the closest color support by the terminal. It is possible that colors in the custom scheme were close to the defaults and ended up being down sampled to the defaults based on the supported colors of the terminals.

From your screenshot I can see the greens/reds not standing out all that much. I'd suggest opening a new issue for that to keep it distinct from this one. I'll close this one for now but in case you're still not able to change the line or tag text color let me know and I'll have a second look.
