### ISSUE TITLE
Feature request: edit appearance of price quote

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#13]
Would it be possible to edit the appearance of the quoted price for the stock? Things like font size, bold, and font color would be nice to edit to make the price stand out more I think. It would also be nice to be able to move it to a different position on the screen closer to the center of the screen imo.

Edit: I see now why the price quote is on the far right, it is to make room for the holdings column. I still think being able to adjust the appearance would be good though.

**Comment by achannarasappa** [comment]
Font is something that is set in your personal terminal
