### ISSUE TITLE
Option to convert to a currency only the Summary line

### ISSUE THREAD

**Issue by gabrielpres** [achannarasappa/ticker#131]
Hi, congrats on this very useful app. If I may add a feature suggestion, it would be the option of showing only the summary (total value, total change, total daily change) in a different currency, while leaving the currencies of the lots and watchlist in the relevant market currencies. I think this would leave the correct level of detail for the single lots (e.g. current price in the actual market), while giving the useful info of total value in the user's local currency. If I understand correctly, this is not the current behaviour, as all prices and cost (lots, watchlist) would be changed to the selected currency. Ideally, when other than the default USD, the summary line should show the currency symbol (EUR, CHF, AUD...). Thanks.

**Comment by achannarasappa** [comment]
Thanks for the suggestion

It makes sense to me to include this in a future release.

**Comment by achannarasappa** [comment]
Added in the latest release
