### ISSUE TITLE
Day range low to high (instead of high to low)

### ISSUE THREAD

**Issue by mjross** [achannarasappa/ticker#135]
In the terminal window where the ticker data is displayed, the "Day Range" values are listed with the high value first and then the low value, which is the opposite of standard practice for every such price range I have ever seen – in fact, any value range outside of financial markets. For instance, in mathematics, an inclusive range of the values from 2 to 3 would be shown as "[2, 3]" and not "[3, 2]". The Ticker day range values would be more intuitive and faster to comprehend if changed to the order used everywhere else and expected by users: low to high. Thank you!

**Comment by achannarasappa** [comment]
Thanks for noticing this and reporting. This is a bug that was introduced when I switched from using the day range property returned by the API to building the range from the underlying values themselves. I'll schedule a fix for an upcoming release

**Comment by mjross** [comment]
Very good. Thanks!

**Comment by achannarasappa** [comment]
Fixed in latest release

**Comment by mjross** [comment]
Much appreciated!
