### ISSUE TITLE
Getting Permission Denied on .ticker.yaml file

### ISSUE THREAD

**Issue by tmack8080** [achannarasappa/ticker#136]
Created a $HOME/.ticker.yaml file with the contents from the read me:
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
currency: USD
watchlist:
  - NET
  - TEAM
  - ESTC
  - BTC-USD

Receive the following error from the CLI:
~$ ticker --config .ticker.yaml

Invalid config: open .ticker.yaml: permission denied

Permissions on the file:
My user is the owner and group. The file has -rw-rw-r-- permissions set.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Terminal: MobaXterm
 - Terminal Version: 20.6
 - ticker Version: 3.1.9

![ticker-permission-denied](https://user-images.githubusercontent.com/22790644/109404923-deeaee80-7938-11eb-8bc3-ff3ef166b58b.png)

**Comment by achannarasappa** [comment]
Would you mind trying to run this within a VM or docker container? Although your file permissions look okay, this sort of issue is typically machine specific

You could also  try opening the file with vim (e.g. `vim .ticker.yaml`) to see if a similar error is raised

**Comment by tmack8080** [comment]
Hi Ani,

I am running this Ubuntu 20.04 VM on MS Hyper-V, on a Windows 10
workstation.

I am able to edit the file without issue using Nano & VI.

I tried this on a native Windows 10 workstation and it works as expected.
I'm fine with that.

I'm happy to continue troubleshooting if you want to find the root cause
but for now I'll use Windows.

Thanks.

**Comment by randlet** [comment]
I also had the same error on Ubuntu 18.04 using the snap package.  Installing using the general Linux install instructions worked fine though.

**Comment by tmack8080** [comment]
I too used the Snap installer. I'll try again with a manual install.

Thanks

**Comment by achannarasappa** [comment]
Thanks @randlet and @tmack8080 that's a really useful detail. I'll have a look at the snap package and see what's wrong there

**Comment by achannarasappa** [comment]
This was fixed in the latest release. See #148 which mentions the same issue.

**Comment by randlet** [comment]
Thanks!
