### ISSUE TITLE
Lot not showing correct number

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#14]
I followed the instructions to input a lot in the .yaml file but it is not appearing. Instead in the place that it should be is just the same number showing the current stock quote.

**Comment by achannarasappa** [comment]
@viperperidot would you be able to share your `.ticker.yaml`?

**Comment by viperperidot** [comment]
# ~/.ticker.yaml
show-tags: true
show-fundamentals: true
show-separator: true
interval: 5
watchlist:
  - SLV
  - NOK
  - BB
  - WFG
  - SPY
  - TSLA
  - GME
lots:
  - symbol: "GME"
    quantity: 1.0
    unit_cost: 380.00

**Comment by viperperidot** [comment]
> @viperperidot would you be able to share your `.ticker.yaml`?

How do I paste the code like you did here in the correct format?

**Comment by viperperidot** [comment]
Is there anything I can do to get this to display properly?

**Comment by viperperidot** [comment]
Is there a fix for this?... Seems like a pretty major feature for this project that should be working.

**Comment by viperperidot** [comment]
Do you need a screenshot or something?

I copied your config example exactly so I dont think there is anything wrong with the .yaml.
