### ISSUE TITLE
ticker app exits when trying to scroll with arrow keys or pgup/pgdn

### ISSUE THREAD

**Issue by quant9** [achannarasappa/ticker#140]
**Describe the bug**
I am unable to scroll up / down with the arrow keys or page-up/page-down keys. Instead of scrolling, the app exits instead (as if I pressed q or ctrl+c). I also tried scrolling with the wheel to no success.

**To Reproduce**
Opening Ticker app on my terminal results in this issue.

**Expected behavior**
I am not aware of any other ways to scroll.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10
 - Terminal: ConEmu (bash)
 - Terminal Version: 180626
 - Font: (Optional) [e.g. Powerline]
 - ticker Version: 2.1.0

**Additional context**

**Comment by achannarasappa** [comment]
Please try with the latest version and let me know if the issue is still occurring.

**Comment by achannarasappa** [comment]
Is there any error message that is printed when this happens?
