### ISSUE TITLE
Spaces + icons showing up as squares / question marks

### ISSUE THREAD

**Issue by quant9** [achannarasappa/ticker#141]
**Describe the bug**
Certain characters, specifically spaces and the round circle icon, are not rendering correctly. Spaces show up as squares while icons show up as question marks.

**To Reproduce**
Run `ticker` with the default ~/.ticker.yaml file per the example in https://github.com/achannarasappa/ticker#configuration.

**Expected behavior**
Characters should not be rendering incorrectly

**Screenshots**
![image](https://user-images.githubusercontent.com/4811862/110027618-3229bc00-7d00-11eb-93a6-0fdaebe7dc12.png)

**Environment (please complete the following information):**
- OS: Windows 10
- Terminal: ConEmu (bash)
- Terminal Version: 180626
- Font: (Optional) [e.g. Powerline]
- ticker Version: 2.1.0

**Additional context**

**Comment by achannarasappa** [comment]
You will need to use a font that supports the unicode characters used by ticker. Have a look at the readme for more info.

I use _DejaVu Sans Mono_ with ConEmu on Windows 10 and the proper characters are rendered.
