### ISSUE TITLE
Quantity showing up screwy

### ISSUE THREAD

**Issue by dtcooper** [achannarasappa/ticker#143]
**Describe the bug**

As pictured below, the quantity is showing up screwy for large amounts for symbol `EB`.

**To Reproduce**
Set this in `lots` in `~/.ticker.yaml`,

```yaml
lots:
  - symbol: EB
    quantity: 100000
    unit_cost: 2.27
```

**Expected behavior**
Quantity shows up as `38;5;27m2274000.00` instead of `100000`

**Screenshots**
![Screenshot of bug](https://user-images.githubusercontent.com/873944/110254595-d2305100-7f5d-11eb-9618-636f04c01a20.png)

**Environment (please complete the following information):**
 - OS: macOS
 - Terminal: macOS terminal app
 - Terminal Version: Version 2.11 (440), whatever ship with latest macOS Big Sur 11.2
 - Font: (Optional) SF Mono Regular, Size 11
 - ticker Version: v4.0.1, from Homebrew

**Additional context**
When I unset `TERM`, ie `TERM="" ticker` it works fine without colours.

Thanks!

**Comment by achannarasappa** [comment]
Fixed in latest release - added 3 additional digits of space
