### ISSUE TITLE
Support for plug :home in snap interface configuration

### ISSUE THREAD

**Issue by secf00tprint** [achannarasappa/ticker#148]
**Problem Statement**
Currently using ticker with snap has problems opening a configuration file presumably because of the sandboxed environment:
![grafik](https://user-images.githubusercontent.com/1818452/110770242-639f0c00-8259-11eb-850b-66c7189edfa4.png)

I used a non-hidden file because [https://snapcraft.io/docs/home-interface](https://snapcraft.io/docs/home-interface) states

> home allows access to non-hidden files owned by the user in the user’s home ($HOME) directory.

The current behavior is also true if you just use: `~/.ticker.yaml`

**Proposed Solution**
Please add a plug `:home` (cf [https://snapcraft.io/docs/interface-management](https://snapcraft.io/docs/interface-management) so 
that it is possible to add the home folder containing a configuration file to the sandbox like

`snap connect ticker:home :home`

**Additional context**
Problems with that in Ubuntu 20.10, snap 2.49

**Comment by achannarasappa** [comment]
Thanks for reporting this issue. I've put out a new release which I believe addresses this. as you stated, you will need to use a non-dot-prefixed file and use the `--config` option to explicitly set the config file location for this to work. 

I'll close this issue but do reopen if it still occurs.
