### ISSUE TITLE
Feature request: Override config file watchlist from command line

### ISSUE THREAD

**Issue by nikcorg** [achannarasappa/ticker#149]
**Problem Statement**
In my `.ticker.yaml` I have my portfolio and other long-term interest stocks configured. Sometimes I would just like to ad-hoc follow one or a few stocks on their own.

**Proposed Solution**
Give command line configuration higher precedence than that in a config file, or add a flag to ignore the config file.

**Alternatives**
Using a second config file is an option that is a working solution already today, but the command line alternative would be a lesser hassle than updating a configuration file and specifying it on the command line.

Using an empty config file removes the need to edit the alternative config file, but doesn't remove the need to specify the alternative config. 

I've used shell aliases to satisfy the use case (in reverse) for now, which is ostensibly a good enough solution, but I still think the feature is worth considering.

**Use Cases**
Sometimes it would be useful to be able to follow one or a few stocks without obscuring them within your larger set of stocks on your watchlist or in your portfolio.

**Additional context**
None

**Comment by achannarasappa** [comment]
Thanks for the suggestion - would you be able to elaborate on how this would differ from the `-w` option which overrides the config watchlist? From your description of the proposed solution, this functionality already exists but it's possible I am not understanding your suggestion.

**Comment by nikcorg** [comment]
@achannarasappa apologies if I was unclear. I was hoping that it would omit any configured stocks and exclusively display the stocks on the provided watchlist.

Currently, I can as you say override the watchlist, but any holdings will still also be displayed. I've tried including `--show-holdings=false`, but the list is still displayed.

**Comment by 097115** [comment]
I second @nikcorg, would be great to be able to launch `ticker` **without the current portfolio**, and neither placing `show-holdings: false` in the configuration file, nor setting it to false at the command line don't seem to work.

**Comment by achannarasappa** [comment]
Thanks for the input and details - it seems like the `--show-holdings=false` is certainly a bug. I'll have a closer look at this one.

As a workaround, removing the `show-holdings` flag from config entirely _should_ address the issue but I agree a permanent fix is needed since the current behavior is unintuitive.

**Comment by 097115** [comment]
> As a workaround, removing the show-holdings flag from config entirely 

You sure? I'm probably missing something but my config is something like this:

    show-tags: false
    show-fundamentals: true
    show-separator: true
    sort: "user"
    currency: USD
    interval: 10
    watchlist:
      - ....
    lots:
      - ....

And then I just launch `ticker` with no additional flags -- and no, my holdings are still shown? :)

**Comment by achannarasappa** [comment]
@097115 definitely a bug then :)

Thank you both for reporting this and providing details

**Comment by 097115** [comment]
@achannarasappa 

I saw you added  this fix, b645616, *"do not show position when flag is not set"*, which potentially could allow to use a workaround described above, to exclude holdings by removing the `show-holdings` flag while viewing tickers not from the configuration file.

However, as you are probably aware, it doesn't completely solves it:
  - if I do not set `show-holdings` flag neither in `.ticker.yaml`, nor via command line
  - and then I launch `ticker` with a temp watchlist
  - it still shows my holdings, just not as holdings (with no position info) but as other entries from the watchlist.

Like:
  - If I have, let's say, BA and LMT in my holdings in `.ticker.yaml`
  - and then launch `ticker --watchlist=AAPL,MSFT`
  - I still see a watchlist of 4 entries, BA, LMT, AAPL and MSFT :)

As I said, you re probably aware of this, and I'm just making some haste here, but just wanted to give you a quick feedback :)

Thanks for your work!

**Comment by achannarasappa** [comment]
I did in fact forget about this bug so I appreciate the reminder :)

I've just put out a new release that addresses this problem. Let me know if you're still seeing the issue and I'll have a second look - in the meantime I'll close this issue.
