### ISSUE TITLE
Feature Request: flag to disable the bottom bar

### ISSUE THREAD

**Issue by randomprey** [achannarasappa/ticker#150]
I use i3 and open ticker up as a floating window. Sometimes when total value goes to three digits it will cause the status bar on the bottom to duplicate and show twice.

Add startup/config flag to disable the bottom bar
--status=off/on
status: off/on

Thanks for the cool terminal app!

**Comment by achannarasappa** [comment]
Thanks for raising this issue

The duplicate bottom bar seems like a bug to me and thus the solution should be a fix for the duplication rather than an option to disable the bar entirely.

**Comment by randomprey** [comment]
Can it be both? I like control over what's displayed on my terminals.

**Comment by achannarasappa** [comment]
I've fixed the duplicate bottom bar bug in the latest release.

I completely understand that you'd want to customize your terminal experience and if you'd like to remove the bottom bar I'd suggest creating a fork and removing it there (have a look in `ui.go` at the footer function). I don't think the bottom bar should be optional in the mainline version.
