### ISSUE TITLE
Previous Close and Open values for ^DJI & YM=F, ^IXIC & NQ=F

### ISSUE THREAD

**Issue by realchrislovett** [achannarasappa/ticker#153]
Previous close and Open values for Dow Jones Industrial Average (^DJI & YM=F) as well as NASDAQ (^IXIC & NQ=F) does not display correctly.

ticker.yaml configuration is as follows

```
sort: user
show-summary: true
show-tags: true
show-fundamentals: true
show-separator: true
show-holdings: true
interval: 5
currency: USD
watchlist:
  - ^GSPC
  - ^IXIC
  - ^DJI
  - ES=F
  - NQ=F
  - YM=F
```

<img width="1680" alt="Screen Shot 2021-03-14 at 11 47 19 PM" src="https://user-images.githubusercontent.com/57230137/111101124-a09c2480-851f-11eb-9138-4853b502917a.png">

**Comment by achannarasappa** [comment]
Thanks for reporting this. The bug has been fixed in the latest release - have a look and let me know if it still occurs for you
