### ISSUE TITLE
Change formatting glyphs

### ISSUE THREAD

**Issue by awgolas** [achannarasappa/ticker#154]
I've been looking for an option to an option to manually change the formatting glyphs, but I can't find one. The horizontal separator works fine, but there's some characters which don't render and I can't figure out where they're set in the source code. 
![image](https://user-images.githubusercontent.com/43121733/111365490-eadced00-8668-11eb-9128-b8def531c9f2.png)

An ability to change or remove the  glyphs would be very helpful. I'd like to avoid the hassle of changing my rendering font just so ◉ and others can show up properly in terminal.

EDIT:
I found the problematic glyphs in the summary.go and watchlist.go files, but changing them to something my terminal could display caused tests fail.

**Comment by achannarasappa** [comment]
Thanks for the suggestion

The glyphs are something that I feel are core the application and function to express things such as market state and direction of change. For that reason, I don't think glyphs could be made optional.

That being said, I understand that you would not want to change your font for one application. If you're open to it, I'd suggest maintaining a fork wherein the glyphs have been replaces with something else of your choosing. Another more robust solution would be to open a PR that would gracefully degrade the glyphs based on what is supported by the font.
