### ISSUE TITLE
Support for non-US stock tickers

### ISSUE THREAD

**Issue by freznicek** [achannarasappa/ticker#155]
**Problem Statement**
At the moment app does not support some European stock tickers, for instance [SXR8](https://www.morningstar.co.uk/uk/etf/snapshot/snapshot.aspx?id=0P0000OO21) or [IUIT](https://www.morningstar.co.uk/uk/etf/snapshot/snapshot.aspx?id=0P000171ZT)

**Proposed Solution**
Add support for European stocks (at least London stock exchange and EU Xetra).

**Use Cases**
Smart investors diversify and hold positions in different parts of the world. Let's support that by adding European stock exchange data sources.

**Comment by achannarasappa** [comment]
European stocks are supported: `ticker -w SXR8.DE,IUIT.L`
