### ISSUE TITLE
Swap Quantity and Avg. Cost lines?

### ISSUE THREAD

**Issue by 097115** [achannarasappa/ticker#160]
**Problem Statement**

First of all, a screenshot:
https://i.imgur.com/Gg8bYQD.png

As you see, of the two lines informational row for a ticker, `Avg. Cost` for holdings shows on the second line, while the current price on the first one. And both represent one kind of information, the **price** :)

**Proposed Solution**
Taking aforesaid into consideration, wouldn't it be more logical to swap `Quantity` and `Avg. Cost` lines in this new column, so that we won't need move our eyes up and down?

Of course, it's less of a *real problem* but this visual consistency does matter, too :)

**Comment by achannarasappa** [comment]
Thank you for the suggestion - I agree it's easier to understand pricing information in a single line. 

I've pushed a commit for the change and it will be available in the next release. I'll leave the issue open until then.
