### ISSUE TITLE
About the stock price for the Brazilian stock exchange (BVMF)

### ISSUE THREAD

**Issue by mozgbrasil** [achannarasappa/ticker#162]
**Problem Statement**

Hello my friend good morning

I would like to inform you that the stock price for the stock exchange in Brazil  (BVMF) is not working

	ticker -w PEAB3,PEAB4

**Proposed Solution**
 

**Alternatives**
 

**Use Cases**
 

**Additional context**

**Comment by achannarasappa** [comment]
Hey @mozgbrasil, in this case, the symbols for these companies differ slightly that what you might expect. Give this a shot:

```
ticker  -w PEAB3.SA,PEAB4.SA
```

I was able to find these symbols by finding the companies on the Yahoo Finance site and locating their corresponding symbols.
