### ISSUE TITLE
Alternative 40-column view for portrait screens

### ISSUE THREAD

**Issue by emulti** [achannarasappa/ticker#165]
Perhaps you could consider adding a runtime option to format the output for tall, narrow screens (40 columns instead of 80). This would allow the program to be used on phones, tablets and other devices with portrait mode as the default use case. 

Each data record would then be double the existing height, with the price data on the first lines, and supplementary data such as high/low, position value and day change on the second. Effectively, text wrap with the line break at a sensible point such as 40 columns. 

An alternative would be to allow narrow 40-column terminals to display a limited subset of the available data up to the visible width.

I ran into the terminal-width issue when porting to a Pinephone (linux) phone, (720 x 1440 display) where the terminal width in portrait mode is 44 columns. I suspect it applies to most 'portrait' devices.

**Comment by achannarasappa** [comment]
Thanks for this suggestion and details on your use case - I certainly had not considered phones and screens with that sort of aspect ratio in the design.

I'd be open to collaborating on a design if you'd be interesting to opening a PR.

**Comment by emulti** [comment]
I'm not a Go programmer so can't offer a PR, but this attachment mocked-up in a spreadsheet gives some idea what I mean. I have used the data from the first stock in your ticker-all-options.png as a source and tried to group price data logically.
The Range and Prev Close/Open lines would only appear if the command-line option for them was included.
Avg. cost and the portfolio positions would only appear if transaction data was available in ticker.yaml

Is a layout like this technically feasible?

![Screenshot from 2021-04-15 12-32-03](https://user-images.githubusercontent.com/7505390/114862627-a8810a00-9de6-11eb-8ff7-c901ba25f4b4.png)
