### ISSUE TITLE
Seeking Guidance: not showing color

### ISSUE THREAD

**Issue by DonZheng** [achannarasappa/ticker#170]
Environment: inatall on Ubuntu 20.10 from AWS Lightsail. Access via putty from windows 10.

ticker installed as per README and .ticker.yaml copied/pasted for testing. 

Everything runs find except that no colors are being applied (showing black background with white fonts only).

New to Ubuntu and ticker. Any guidance/advice is much appreciated.

![image](https://user-images.githubusercontent.com/40833875/117669751-95e1d100-b1ea-11eb-974a-3290b03a3255.png)

**Comment by DonZheng** [comment]
Dear @achannarasappa ,

Thanks HEAPS for your timely reply! Really appreciate it!

By following the link your shared, I can see the ticker showing colors now.

![image](https://user-images.githubusercontent.com/40833875/117707900-7c547f80-b212-11eb-826b-cc93d1c246a6.png)

Best Wishes

**Comment by achannarasappa** [comment]
Glad to hear you got it working!
