### ISSUE TITLE
HTTP request connection refused

### ISSUE THREAD

**Issue by jdqw210** [achannarasappa/ticker#183]
Get "https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&fields=regularMarketPrice,currency&symbols=AAPL": dial tcp: lookup query1.finance.yahoo.com on 192.168.1.99:53: read udp 192.168.1.99:58769->192.168.1.99:53: read: connection refused

Was working fine on Friday, now I receive this error.

Can replicate error by running tickers on the CLI

**Comment by jdqw210** [comment]
I can WGET the request string and Yahoo returns the json data just fine

**Comment by achannarasappa** [comment]
This looks like a local DNS issue of some kind since the error is saying that it can't reach a local network DNS server at 192.168.1.99. It's not clear to me what the specific issue is given a `wget` works okay.

**Comment by jdqw210** [comment]
Indeed there was a problem with dnsmasq, thank you for the help
