### ISSUE TITLE
Document how to map to host .ticker.yaml file when using docker image  

### ISSUE THREAD

**Issue by faustinoribeiro** [achannarasappa/ticker#185]
I might have missed something in the documentation or used the docker image incorrectly, but I could not get my config to load when running the docker image.

The only way I got it to work is by running:
docker run -it --rm -v ~/.ticker.yaml:/.ticker.yaml achannarasappa/ticker 
with in my case .ticker.yaml being at the root of my home folder.

Again, it might be an error on my side, but the way on how to use the docker image didn't work out of the box in my case. Either there is a bug or the documentation is incomplete.

Running Linux Mint 20.2 and Pop!_OS latest version (issue shows on both systems)

**Comment by achannarasappa** [comment]
Thanks for suggesting this. I can see how it's not obvious how to do this from the readme as is. I've updated it to include when you mentioned.
