### ISSUE TITLE
Historical Data

### ISSUE THREAD

**Issue by ytbor11** [achannarasappa/ticker#196]
Awesome program, BTW. Thanks for working on it and  making it available. I recently started something similar in Java. But, yours is comprehensive and the output/display looks much nicer. 

A couple of thoughts/feature requests:
- having the ability to track a portfolio's performance over a given time period (#days in the past). For example, Lets say I have a portfolio with 100 units of VTSAX and 50 units of VBTLX and 20 units of  AAPL. I want to track its performance over the last month/3 months/year etc. (given in # of days). Track the perf of the whole portfolio, not necessarily individual components. Currently, I can do this by putting historical prices for cost basis in yaml file. But looking for something more streamlined.

- Second comment. Not sure what you're using for the stock data API, but some stock/ETF numbers are off. They seem accurate for mutual funds though. In my experience, Yahoo Finance API provides more accurate data. Numbers from Google Finance API are off many times. I can run more tests and provide additional data if needed.

Thanks again for working on this.

**Comment by achannarasappa** [comment]
Thanks for the positive feedback and suggestions!

> having the ability to track a portfolio's performance over a given time period (#days in the past)
This is an interesting idea and would be useful to include in a broader dashboard or summary page. With the current summary view, it may end up being a bit crowded. I'd be interested to see if there's wider community interest in this. In the meantime, #99 could make it a bit easier to track multiple historical cost bases as separate group but it would end up having the same friction points you mention with using multiple configs

> Numbers from Google Finance API are off many times. I can run more tests and provide additional data if needed.
ticker is using Yahoo finance and some of the discrepancies could be explained by polling intervals. If there's other data sources out there without authentication requirements that could be used instead I would be interested to hear about them.
