### ISSUE TITLE
zsh: killed ./ticker

### ISSUE THREAD

**Issue by proyb6** [achannarasappa/ticker#2]
On Apple M1 running Big Sur

**Comment by achannarasappa** [comment]
Adding a link to the reddit thread related to the issue:  https://www.reddit.com/r/golang/comments/l8poy7/ticker_a_terminal_stock_watcher_and_stock/glep2pg?utm_source=share&utm_medium=web2x&context=3

**Comment by itsamoreh** [comment]
I'm getting a similar issue.

- MacOS Big Sur
- Intel
- iTerm / zsh
- Installed with brew like this: `brew install achannarasappa/tap/ticker`

```
~ ➤ ticker -w GME
[1]    24785 killed     ticker -w GME
```

**Comment by eshack94** [comment]
Reporting that version 2.0.2 has fixed the issue. See the reddit thread linked for the discussion about this. It looks like `upx` was causing an issue on Big Sur.

**Comment by achannarasappa** [comment]
thanks @eshack94!

Closing this issue
