### ISSUE TITLE
Timeout from finance.yahoo.com

### ISSUE THREAD

**Issue by zachary** [achannarasappa/ticker#202]
Get "https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&fields=regularMarketPrice,currency&symbols=": dial tcp: lookup query1.finance.yahoo.com on 172.30.208.1:53: read udp 172.17.0.2:58520->172.30.208.1:53: i/o timeout

Could you please help to check this above?
Thanks

**Comment by achannarasappa** [comment]
Could you try issuing a cURL request directly to that url? More often than not these issues are proxy / VPN / user network related
