### ISSUE TITLE
Bug: last group of yml config file is not displayed

### ISSUE THREAD

**Issue by baschdello** [achannarasappa/ticker#206]
**Describe the bug**
The last group of groupsection from yml file is not displayed.

**To Reproduce**
1. I created 2 groups at yml config file, each with watchlist and holdings
2. if starting ticker with this yml config file and try to tab through groups, only the default group and first group listed in yml file is displayed
3. if I duplicate the last group in yml config file this group is shown at tabbing through the groups.

**Expected behavior**
The last group in yml config file should be displayed without duplicating it in config file.

**Environment (please complete the following information):**
 - OS: Linux
 - ticker Version: v4.4.1

**Additional context**
Without having a look at the new code, I think this is a simple boundary check problem at a loop.

**Comment by achannarasappa** [comment]
Thanks for reporting this. I've fixed this in the latest release v4.4.2

Let me know if you are still experiencing the issue
