### ISSUE TITLE
Support additional cryptocurrencies

### ISSUE THREAD

**Issue by krzyk** [achannarasappa/ticker#212]
**Problem Statement**
Yahoo Finance doesn't have all the cryptocurrencies, e.g. TONCOIN, or PLANETS.

**Proposed Solution**
Use another source for crypto that is not found in Yahoo, e.g. cryptocompare, for PLANETS-USD: `https://min-api.cryptocompare.com/data/price?fsym=PLANETS&tsyms=USD`

**Alternatives**
Sit and wait for Yahoo adds less popular cryptocurrencies?

**Comment by achannarasappa** [comment]
Thanks for the suggestion! This makes sense to me to add and there's already some foundational code in place to support multiple data sources.

**Comment by achannarasappa** [comment]
Added in the latest release
