### ISSUE TITLE
Have shift+tab cycle groups backwards

### ISSUE THREAD

**Issue by joce** [achannarasappa/ticker#221]
**Problem Statement**
Right now, pressing the <kbd>tab</kbd> key cycles the groups forward. However, there is no way to cycle them backwards. 

**Proposed Solution**
Pressing <kbd>shift</kbd>+<kbd>tab</kbd> should cycle in the reverse order.

**Alternatives**
_No alternatives provided_

**Use Cases**
When having multiple groups (3 or more) and you want to just toggle between two adjacent ones, it would be quite useful to have a way to cycle in the reverse order.

**Additional context**
_No additional context provided_

**Comment by deroshkin** [comment]
This currently seems impossible without an upstream patch to https://github.com/charmbracelet/bubbletea, which ticker uses for input handling. I've played around, and bubbletea reports `shift`+`tab` as `tab`.

One alternative could be to add left and right arrow keys as options for cycling between groups. If this sounds like a good idea, I have a patch ready

**Comment by achannarasappa** [comment]
Closing since this was added in a recent release
