### ISSUE TITLE
Add GPL disclaimer

### ISSUE THREAD

**Issue by werdahias** [achannarasappa/ticker#230]
It would be nice is this repo had a disclaimer included in the README. Like "This program is free software, you are free to ..." .
This would improve the documentation of this project.

**Comment by achannarasappa** [comment]
There is a [LICENSE file](https://github.com/achannarasappa/ticker/blob/master/LICENSE) included in the repository. If you had something else in mind, it'd be interested in seeing an example so I can understand better what you had in mind.
