### ISSUE TITLE
Adding to configure sorting order

### ISSUE THREAD

**Issue by ChangheeOh** [achannarasappa/ticker#234]
**Problem Statement**
I tried to add a property in configure to substitute `ticker --sort user` command and failed. 

**Proposed Solution**
Please adding `sort` property in `.ticker.yaml` to set sorting order.

**Alternatives**
N/A

**Use Cases**
N/A

**Additional context**
N/A

**Comment by yodigi7** [comment]
This issue seems to be able to closed, right?
