### ISSUE TITLE
ticker only show the price

### ISSUE THREAD

**Issue by StingJohnson** [achannarasappa/ticker#235]
hi developer,
is there a way when i type for example "ticker btc" and it only shows the price, just the price, nothing else.
thanks alot.

**Comment by achannarasappa** [comment]
I suggest using the [print option](https://github.com/achannarasappa/ticker#printing-holdings) to achieve something similar. You can use a text processing tool like `sed`, `grep`, or `awk` to filter from there to the output you want. Using the Yahoo or Coingecko API directly is likely to be simpler though.
