### ISSUE TITLE
Ticker hangs at startup

### ISSUE THREAD

**Issue by ajgringo619** [achannarasappa/ticker#237]
**Describe the bug**
Ticker screen opens blank, never updates any configured assets

**To Reproduce**
1. Start `ticker --config $HOME/.config/ticker/ticker.yaml`
2. Header/footer appear, but no stock data

**Environment (please complete the following information):**
 - OS: Linux [EndeavourOS]
 - Terminal: [xfce4-terminal]
 - Terminal Version: [1.0.4]
 - ticker Version: [4.5.4]

**Additional context**
When I run this command (from your source) - curl "https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&fields=regularMarketPrice,currency&symbols=IBM" - it works. https://finance.yahoo.com works as expected. A data test with **yfinance** also works, so this doesn't seem like a connection problem.

This has been working for months (updated on 2022-09-17), up until about an hour ago.

**Comment by achannarasappa** [comment]
Thanks for reporting this! It looks like there was a change in the schema of the data being returned by the Yahoo. Having a closer look to see what needs to be changed

**Comment by achannarasappa** [comment]
Just released v4.5.5 which should fix the majority of broken cases. There's likely a few I missed which will become evident over time e.g. the indicator for market state change from `POST` to `POSTPOST` 

I'll keep this issue open for a few days in case there's reports of other similar issues.

**Comment by ajgringo619** [comment]
Working as expected - thanks a bunch!

**Comment by eriknh** [comment]
Thanks for the quick fix.

**Comment by jayray-git** [comment]
Test files fail when building from source:

go test ./...

?   	github.com/achannarasappa/ticker	[no test files]
?   	github.com/achannarasappa/ticker/cmd	[no test files]
ok  	github.com/achannarasappa/ticker/internal/asset	(cached)
ok  	github.com/achannarasappa/ticker/internal/cli	(cached)
ok  	github.com/achannarasappa/ticker/internal/cli/symbol	(cached)
?   	github.com/achannarasappa/ticker/internal/common	[no test files]
ok  	github.com/achannarasappa/ticker/internal/currency	(cached)
Running Suite: Print Suite - /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print
==========================================================================================
Random Seed: 1674251734

Will run 2 of 2 specs
------------------------------
• [FAILED] [0.000 seconds]
Print
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:29
  Run
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:35
    [It] should print holdings in JSON format
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:72

  Expected
      <string>: null\n
  to equal
      <string>: [{\"name\":\"Alphabet Inc.\",\"symbol\":\"GOOG\",\"price\":\"2838.420000\",\"value\":\"28384.200000\",\"cost\":\"10000.000000\",\"quantity\":\"10.000000\",\"weight\":\"96.996890\"},{\"name\":\"Roblox Corporation\",\"symbol\":\"RBLX\",\"price\":\"87.880000\",\"value\":\"878.800000\",\"cost\":\"500.000000\",\"quantity\":\"10.000000\",\"weight\":\"3.003110\"}]\n
  In [It] at: /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:76
------------------------------
• [FAILED] [0.000 seconds]
Print
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:29
  Run
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:35
    the format option is set to csv
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:79
      [It] should print the holdings in CSV format
      /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:80

  Expected
      <string>: name,symbol,price,value,cost,quantity,weight\n\n
  to equal
      <string>: name,symbol,price,value,cost,quantity,weight\nAlphabet Inc.,GOOG,2838.42,28384,10000,10.000,96.997\nRoblox Corporation,RBLX,87.880,878.80,500.00,10.000,3.0031\n\n
  In [It] at: /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:87
------------------------------


Summarizing 2 Failures:
  [FAIL] Print Run [It] should print holdings in JSON format
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:76
  [FAIL] Print Run the format option is set to csv [It] should print the holdings in CSV format
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/print/print_test.go:87

Ran 2 of 2 Specs in 0.000 seconds
FAIL! -- 0 Passed | 2 Failed | 0 Pending | 0 Skipped
--- FAIL: TestPrint (0.00s)
FAIL
FAIL	github.com/achannarasappa/ticker/internal/print	0.004s
Running Suite: Quote Suite - /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote
==========================================================================================
Random Seed: 1674251734

Will run 2 of 2 specs
------------------------------
• [FAILED] [0.000 seconds]
Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/quote_test.go:65
  GetAssetGroupQuote
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/quote_test.go:78
    [It] should get price quotes for each asset based on it's data source
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/quote_test.go:80

  Expected
      <[]common.AssetQuote | len:0, cap:0>: nil
  to have length 2
  In [It] at: /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/quote_test.go:109
------------------------------
•

Ran 2 of 2 Specs in 0.000 seconds
FAIL! -- 1 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestQuote (0.00s)
FAIL
FAIL	github.com/achannarasappa/ticker/internal/quote	0.004s
ok  	github.com/achannarasappa/ticker/internal/quote/coingecko	(cached)
Running Suite: Yahoo Quote Suite - /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo
======================================================================================================
Random Seed: 1674251734

Will run 15 of 15 specs
------------------------------
•! [PANICKED] [0.000 seconds]
Yahoo Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:15
  GetAssetQuotes
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:16
    [It] should make a request to get stock quotes and transform the response
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:17

  Test Panicked
  In [It] at: /usr/lib/go/src/runtime/panic.go:113

  runtime error: index out of range [0] with length 0

  Full Stack Trace
    github.com/achannarasappa/ticker/internal/quote/yahoo_test.glob..func5.1.1()
    	/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:51 +0x60e
------------------------------
•! [PANICKED] [0.000 seconds]
Yahoo Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:15
  GetAssetQuotes
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:16
    the market is in a pre-market trading session
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:63
      [It] should return the pre-market price
      /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:64

  Test Panicked
  In [It] at: /usr/lib/go/src/runtime/panic.go:113

  runtime error: index out of range [0] with length 0

  Full Stack Trace
    github.com/achannarasappa/ticker/internal/quote/yahoo_test.glob..func5.1.2.1()
    	/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:91 +0x353
------------------------------
•! [PANICKED] [0.000 seconds]
Yahoo Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:15
  GetAssetQuotes
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:16
    the market is in a pre-market trading session
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:63
      there is no pre-market price
      /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:98
        [It] should return the regular market price
        /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:99

  Test Panicked
  In [It] at: /usr/lib/go/src/runtime/panic.go:113

  runtime error: index out of range [0] with length 0

  Full Stack Trace
    github.com/achannarasappa/ticker/internal/quote/yahoo_test.glob..func5.1.2.2.1()
    	/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:123 +0x3cf
------------------------------
•! [PANICKED] [0.000 seconds]
Yahoo Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:15
  GetAssetQuotes
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:16
    the market is in a post-market trading session
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:132
      [It] should return the post-market price added to the regular market price
      /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:133

  Test Panicked
  In [It] at: /usr/lib/go/src/runtime/panic.go:113

  runtime error: index out of range [0] with length 0

  Full Stack Trace
    github.com/achannarasappa/ticker/internal/quote/yahoo_test.glob..func5.1.3.1()
    	/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:160 +0x353
------------------------------
•! [PANICKED] [0.000 seconds]
Yahoo Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:15
  GetAssetQuotes
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:16
    the market is in a post-market trading session
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:132
      there is no post-market price
      /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:167
        [It] should return the regular market price
        /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:168

  Test Panicked
  In [It] at: /usr/lib/go/src/runtime/panic.go:113

  runtime error: index out of range [0] with length 0

  Full Stack Trace
    github.com/achannarasappa/ticker/internal/quote/yahoo_test.glob..func5.1.3.2.1()
    	/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:197 +0x346
------------------------------
•! [PANICKED] [0.000 seconds]
Yahoo Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:15
  GetAssetQuotes
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:16
    the market is closed
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:204
      [It] should return the post-market price added to the regular market price
      /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:205

  Test Panicked
  In [It] at: /usr/lib/go/src/runtime/panic.go:113

  runtime error: index out of range [0] with length 0

  Full Stack Trace
    github.com/achannarasappa/ticker/internal/quote/yahoo_test.glob..func5.1.4.1()
    	/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:231 +0x3cf
------------------------------
•! [PANICKED] [0.000 seconds]
Yahoo Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:15
  GetAssetQuotes
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:16
    the market is closed
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:204
      there is a post market price
      /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:238
        [It] should show a closed state but with the post market change and price
        /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:239

  Test Panicked
  In [It] at: /usr/lib/go/src/runtime/panic.go:113

  runtime error: index out of range [0] with length 0

  Full Stack Trace
    github.com/achannarasappa/ticker/internal/quote/yahoo_test.glob..func5.1.4.2.1()
    	/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:268 +0x3cf
------------------------------
•! [PANICKED] [0.000 seconds]
Yahoo Quote
/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:15
  GetAssetQuotes
  /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:16
    the quote is for a cryptocurrency
    /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:277
      [It] should should set the asset class to cryptocurrency
      /home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:278

  Test Panicked
  In [It] at: /usr/lib/go/src/runtime/panic.go:113

  runtime error: index out of range [0] with length 0

  Full Stack Trace
    github.com/achannarasappa/ticker/internal/quote/yahoo_test.glob..func5.1.5.1()
    	/home/XXX/.cache/yay/ticker/src/ticker-4.5.5/internal/quote/yahoo/yahoo_test.go:306 +0x194
------------------------------
•••••••


Summarizing 8 Failures:
  [PANICKED!] Yahoo Quote GetAssetQuotes [It] should make a request to get stock quotes and transform the response
  /usr/lib/go/src/runtime/panic.go:113
  [PANICKED!] Yahoo Quote GetAssetQuotes the market is in a pre-market trading session [It] should return the pre-market price
  /usr/lib/go/src/runtime/panic.go:113
  [PANICKED!] Yahoo Quote GetAssetQuotes the market is in a pre-market trading session there is no pre-market price [It] should return the regular market price
  /usr/lib/go/src/runtime/panic.go:113
  [PANICKED!] Yahoo Quote GetAssetQuotes the market is in a post-market trading session [It] should return the post-market price added to the regular market price
  /usr/lib/go/src/runtime/panic.go:113
  [PANICKED!] Yahoo Quote GetAssetQuotes the market is in a post-market trading session there is no post-market price [It] should return the regular market price
  /usr/lib/go/src/runtime/panic.go:113
  [PANICKED!] Yahoo Quote GetAssetQuotes the market is closed [It] should return the post-market price added to the regular market price
  /usr/lib/go/src/runtime/panic.go:113
  [PANICKED!] Yahoo Quote GetAssetQuotes the market is closed there is a post market price [It] should show a closed state but with the post market change and price
  /usr/lib/go/src/runtime/panic.go:113
  [PANICKED!] Yahoo Quote GetAssetQuotes the quote is for a cryptocurrency [It] should should set the asset class to cryptocurrency
  /usr/lib/go/src/runtime/panic.go:113

Ran 15 of 15 Specs in 0.178 seconds
FAIL! -- 7 Passed | 8 Failed | 0 Pending | 0 Skipped
--- FAIL: TestQuote (0.18s)
FAIL
FAIL	github.com/achannarasappa/ticker/internal/quote/yahoo	0.182s
ok  	github.com/achannarasappa/ticker/internal/sorter	(cached)
?   	github.com/achannarasappa/ticker/internal/ui	[no test files]
ok  	github.com/achannarasappa/ticker/internal/ui/component/summary	(cached)
ok  	github.com/achannarasappa/ticker/internal/ui/component/watchlist	(cached)
ok  	github.com/achannarasappa/ticker/internal/ui/util	(cached)
?   	github.com/achannarasappa/ticker/test/http	[no test files]
FAIL

**Comment by jayray-git** [comment]
Test fail when running 

go test ./...

[ticker-test-fail.txt](https://github.com/achannarasappa/ticker/files/10470562/ticker-test-fail.txt)

**Comment by Harpo3** [comment]
Using 4.5.5-1 and same issue as OP.

**Comment by achannarasappa** [comment]
@Harpo3 is the issue you're seeing with tests failing or that ticker is hanging? The test failure issue was just addressed in a recent commit.

**Comment by Harpo3** [comment]
> @Harpo3 is the issue you're seeing with tests failing or that ticker is hanging? The test failure issue was just addressed in a recent commit.

Running the AUR version in Arch Linux. Ticker starts but there is nothing in the display. It used to display my positions and quotes.

**Comment by achannarasappa** [comment]
Please check again - the AUR version is not maintained by me and it was likely took some time for the new version to be published.

Closing this issue for now but will reopen if there is still an active issue.
