### ISSUE TITLE
Go-compiler seems to choke on several test files when compiling V 4.5.5.

### ISSUE THREAD

**Issue by WinterStar2** [achannarasappa/ticker#239]
**Version 4.5.5 compilation failure**
Go-compiler seems to choke on "/internal/quote/yahoo/yahoo_test.go" and "quote_test.go", as well as "/internal/print/print_test.go".

**Steps To Reproduce**
Compile Ticker from source. 

**Expected behavior**
Compilation succeeds

**Environment:**
 - OS: ArchLinux
 - Terminal: Alacritty
 - Terminal Version: 0.11.0
 - Font: Terminus / Iosevka
 - ticker Version: 4.5.5

**Comment by ClumsyDerp** [comment]
Can confirm.

 8/15 fail for me and build aborts due to a `failure` in `check()`

Experiencing the same issue on EndeavourOS.

**Comment by reefland** [comment]
Failing on Manjaro too.
```
Ran 15 of 15 Specs in 0.077 seconds
FAIL! -- 7 Passed | 8 Failed | 0 Pending | 0 Skipped
```

**Comment by jakubreron** [comment]
Failing on Arch too, with the same error

**Comment by achannarasappa** [comment]
Thank you all for reporting and sharing info about the issue. The root cause was that the tests were not updated along with the the hoxfix that was applied a few weeks ago to match the new Yahoo API. This should be be working now with the latest release - please reopen if you still see an issue.
