### ISSUE TITLE
Ticker doesn't show stock data

### ISSUE THREAD

**Issue by tkalmi** [achannarasappa/ticker#246]
**Describe the bug**
Similarly to the issue described in https://github.com/achannarasappa/ticker/issues/237, only the empty header and footer of `ticker` are shown, with no stock information whatsoever.

**To Reproduce**
1. Start `ticker --config $HOME/.config/ticker/ticker.yaml`
2. Header/footer appear, but no stock data

**Expected behavior**
I'm expecting data of the stocks I'm following to be shown.

**Screenshots**
Only the empty shell is shown
![image](https://user-images.githubusercontent.com/14164217/233290926-de4ab19c-bebb-4e37-9fc9-c65a730b5a12.png)

**Environment (please complete the following information):**
 - OS: macOS Ventura 13.2.1
 - Terminal: iTerm2 (also tried with macOS default terminal)
 - Terminal Version: Build 3.4.19
 - Font: (Optional) Menlo and MesloLGS NF
 - ticker Version: v4.5.6

**Comment by chrisswanda** [comment]
Confirming I have the same issue.

**Comment by jfbourdeau** [comment]
Same thing here, Montreal Canada. ( Linux Debian Deepin ) 
Since yesterday...

**Comment by Spreadneck** [comment]
Same issue here, began happening in the afternoon CST. I assume it is an API issue because [mop-tracker](https://github.com/mop-tracker/mop) uses the same API and stopped working at the same time.

**Comment by joce** [comment]
The v7 API appears to be broken as @chrisswanda indicated. However, I still can get results using the v6 API:

```bash
$ curl https://query1.finance.yahoo.com/v6/finance/quote?symbols=AAPL,GOOG,F | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  6267  100  6267    0     0  27567      0 --:--:-- --:--:-- --:--:-- 27607
{
  "quoteResponse": {
    "result": [
      {
        "language": "en-US",
        "region": "US",
        "quoteType": "EQUITY",
        "typeDisp": "Equity",
        "quoteSourceName": "Nasdaq Real Time Price",
        "triggerable": true,
        "customPriceAlertConfidence": "HIGH",
        "priceEpsCurrentYear": 28.107447,
        "sharesOutstanding": 15821899776,
        "bookValue": 3.581,
        "fiftyDayAverage": 156.0672,
        "fiftyDayAverageChange": 11.172104,
        "fiftyDayAverageChangePercent": 0.071585216,
        "twoHundredDayAverage": 150.1536,
        "twoHundredDayAverageChange": 17.085709,
        "twoHundredDayAverageChangePercent": 0.11378821,
        "marketCap": 2646043525120,
        "forwardPE": 25.339289,
        "priceToBook": 46.701843,
        "sourceInterval": 15,
        "exchangeDataDelayedBy": 0,
        "firstTradeDateMilliseconds": 345479400000,
        "priceHint": 2,
        "tradeable": false,
        "cryptoTradeable": false,
        "regularMarketPreviousClose": 167.63,
        "bid": 0,
        "ask": 0,
// ...
```

**Comment by mnsrulz** [comment]
same issue here.. hope it will get fix soon.

**Comment by ngocphamm** [comment]
I think it got fixed from the API side. Working now for me.

**Comment by chrisswanda** [comment]
Working now for me also.

**Comment by tkalmi** [comment]
Thanks, seems to be working for me too now 👍 I suppose we label this as a temporary error on the API side, and therefore there's no need to fix anything on ticker's side. Closing the issue.

**Comment by jfbourdeau** [comment]
good for me too ( MTL Canada)

**Comment by achannarasappa** [comment]
Just checked about 30 minutes ago and again now. There was a transient issue with the Yahoo API where it was requiring a a specific cookie that was not set. It likely broke Yahoo Finance's integration as well as ticker's so it looks like they've rolled back. I've re-run the contract tests and they're passing now so ticker should be working again.
