### ISSUE TITLE
Error when connected through VPN

### ISSUE THREAD

**Issue by gabrielpres** [achannarasappa/ticker#249]
**Describe the bug**
I get the following error when connected to the internet via VPN:

Error: Get "https://raw.githubusercontent.com/achannarasappa/ticker-static/master/symbols.csv": write tcp [2a02:aa15:280:6800:78b9:9d9a:50a4:e347]:60943->[2606:50c0:8002::154]:443: write: socket is not connected

When VPN is disconnected, it works normally.
My VPN provider is Mullvad. Not sure if this is a VPN issue or a Ticker issue (it used to work in the past, through the same VPN provider)

**Environment (please complete the following information):**
 - OS: Mac MacOS 13.3.1 (a)
 - ticker Version: v4.5.10

**Comment by gabrielpres** [comment]
It is working again now with Ticker version 4.5.13

**Comment by achannarasappa** [comment]
thanks for the follow up closing this
