### ISSUE TITLE
Yahoo break their endpoint again?

### ISSUE THREAD

**Issue by chrisswanda** [achannarasappa/ticker#250]
curl https://query1.finance.yahoo.com/v6/finance/quote?symbols=GOOG

`{"finance":{"result":null,"error":{"code":"Not Found","description":"HTTP 404 Not Found"}}}`

**Comment by juanandresgs** [comment]
I noticed intermittent results as of a day ago, total outage as of today. :(

**Comment by eriknh** [comment]
Looks like Yahoo is moving to a paid model for this API endpoint per this Google Form: https://docs.google.com/forms/d/e/1FAIpQLSeyb7xMtZFjoNYI7XG1rjlhUopKAxdLAfSRcaPxg9p-9ii-_g/viewform

"Yahoo Finance | API Feedback
We’re sorry for the inconvenience, but API-level access to Yahoo Finance quotes data has been disabled."

This can be seen sourced from the JSON in the reply from https://query1.finance.yahoo.com/v7/finance/quote?symbols=MSFT

![image](https://github.com/achannarasappa/ticker/assets/14324901/5062a05f-5658-4fcd-b090-50b3bccf184a)

![image](https://github.com/achannarasappa/ticker/assets/14324901/beb3ab87-847c-4e5e-b8b6-4f34e3c81941)

**Comment by ktpx** [comment]
Yeah.  Some posted a cookie crumb workaround for v7 of the API, but that doesn't seem to work either anymore 8for me atleast).  This sucks.  Any other free tier APis? I used alpha vantage, before, but they made most useful calls premium.

**Comment by achannarasappa** [comment]
Thanks for reporting this - the latest release (v4.5.13) implements a fix that works with the latest API. Please re-open if this resurfaces.

**Comment by ktpx** [comment]
> Thanks for reporting this - the latest release (v4.5.13) implements a fix that works with the latest API. Please re-open if this resurfaces.

What fix..this doesnt work anymore at all afaik....?

**Comment by chrisswanda** [comment]
It is working for me on version 4.5.13.

**Comment by ktpx** [comment]
> It is working for me on version 4.5.13.
Ok, ,interesting...im not using this software, just wondered what change was implemented, as the ones Ive found aren't working.
