### ISSUE TITLE
Make the yahoo API version configurable

### ISSUE THREAD

**Issue by sarcasticadmin** [achannarasappa/ticker#251]
**Problem Statement**

We have had several of the past releases be due to the yahoo API availability. I hope this stabilizes soon but I think its worth considering alternatives which require less churn than releasing a new version of the ticker application.

See the following issues for context:
  - https://github.com/achannarasappa/ticker/issues/246
  - https://github.com/achannarasappa/ticker/issues/248
  - https://github.com/achannarasappa/ticker/issues/250

**Proposed Solution**

Originally mentioned (https://github.com/achannarasappa/ticker/issues/247#issuecomment-1536376649) by @mattyrad

It would be nice if the Yahoo API endpoint version was configurable via `~/.ticker.yaml`

**Alternatives**

1. Releasing new version of the binary when Yahoo API versions/endpoints change. (Current solution)
2. Switch to an alternative finance API that are more OSS friendly?

**Use Cases**

Allow for self service resolution when the Yahoo API version is moved in the future and decouple this with releases of the ticker application.

**Comment by achannarasappa** [comment]
Thanks for suggesting this - it's something I've been thinking about as well but I don't have a good solution.

Making the API endpoint configurable is not a big lift however I don't know if this makes ticker less fragile. ticker would still be reliant on an API that could return the same responses as the Yahoo API.

> Switch to an alternative finance API that are more OSS friendly?

Definitely open to building support for another API if there's one out there. Ideally the alternate API does not require an API key but there's none I know of out there aside from Yahoo.

Another option is to separate the core of ticker from API integrations and auto-update the integration on first load.

**Comment by sarcasticadmin** [comment]
> Making the API endpoint configurable is not a big lift however I don't know if this makes ticker less fragile. ticker would still be reliant on an API that could return the same responses as the Yahoo API.

Could we have a default for the endpoint (omitting any entry in the `ticker.yaml) and the just make it overridable in the configuration? That way its only explicitly set if/when you know you need it so theres less of a chance of making a mistake due to a typo, etc. I think that would help with the fragility concern.

> Definitely open to building support for another API if there's one out there. Ideally the alternate API does not require an API key but there's none I know of out there aside from Yahoo.

I dont know of any either, but if I come across any Ill include them in a followup.

> Another option is to separate the core of ticker from API integrations and auto-update the integration on first load.

This seems like another good option to consider :+1:
