### ISSUE TITLE
Add notification support

### ISSUE THREAD

**Issue by klownie** [achannarasappa/ticker#255]
**Problem Statement**
Make it so that a warning can be configured to notify the user if an action goes under or over a certain ammount

**Proposed Solution**
This can be donne by running the app a a daemon. For exemple `systemctl eneable ticker.service`

**Comment by smjure** [comment]
Little follow up, is there any plan to implement the alert/notification service? Thank you. It seems it's quite a desired feature with many similar issues/requests opened so far.
