### ISSUE TITLE
Total growth over several groups?

### ISSUE THREAD

**Issue by 097115** [achannarasappa/ticker#258]
**Problem Statement**

When holdings are divided over several groups, the group's statistics, like the day change, the overall change and others are displayed in the top left corner.

However, it would be also quite handy to have some totals from all the groups, too, what would you  say? 

**Proposed Solution**

Of course, the space is limited, so may be you could consider just adding a total overall change from all the groups? For instance, in the top right corner? So that a user could always know, "Oh, gosh, no matter how successful this particular group is, in total I'm still poorer this much" :) 

And, sure, if it fits and doesn't overload the top bar, the total cost could be a thing, too.

Just a thought, and thank you for the app :)

**Comment by achannarasappa** [comment]
Thanks for the suggestion! Definitely open to adding something like this if there's broad interest. Another approach to solve the space issue could be to create a summary page that spans all groups. Interested to hear more feedback and ideas too.
