### ISSUE TITLE
Module path should include repository hostname / path

### ISSUE THREAD

**Issue by b0o** [achannarasappa/ticker#26]
To follow [Go conventions](https://golang.org/ref/mod#module-path) and to make this package `go get`-able, the [module path](https://github.com/achannarasappa/ticker/blob/master/go.mod#L1) should be `github.com/achannarasappa/ticker` and the package import paths should be `github.com/achannarasappa/ticker/{package}`. 

Currently, attempting to `go get github.com/achannarasappa/ticker` (my preferred way of installing go executable programs) fails with:

```
package ticker/cmd: unrecognized import path "ticker/cmd": import path does not begin with hostname
```

**Comment by Gonzih** [comment]
Same problem here

```
$ go get github.com/achannarasappa/ticker
go: downloading github.com/achannarasappa/ticker v1.1.1
go: github.com/achannarasappa/ticker upgrade => v1.1.1
go get: github.com/achannarasappa/ticker@v1.1.1: parsing go.mod:
        module declares its path as: ticker
                but was required as: github.com/achannarasappa/ticker
```

**Comment by achannarasappa** [comment]
I believe I've resolved the problem. Please reopen if that's not the case

**Comment by Gonzih** [comment]
Thanks a lot!
