### ISSUE TITLE
Egads, Watson; there's something afoot! 

### ISSUE THREAD

**Issue by adanhawth** [achannarasappa/ticker#262]
**Problem Statement**
Brittle design.

**Proposed Solution**
Refactor.

**Alternatives**
Do Nothing or switch to the Java platform.

**Use Cases**
It'd be good to do so.  I smell early 2000's corporate Java code here.

**Additional context**
This project could be great, if it weren't brittle.

**Comment by achannarasappa** [comment]
Thanks for the input - could you provide a specific example or two of areas of improvement and suggestions for how you think they could be done differently?
