### ISSUE TITLE
segfault

### ISSUE THREAD

**Issue by herby-popnecker** [achannarasappa/ticker#267]
**Describe the bug**

segmentation fault when launching on rPi 5

**To Reproduce**
1. Downloaded ticker-4.5.14-linux-arm64.tar.gz
2. tar -xvf ticker.....
3. chmod +x ticker
4. sudo mv ticker /usr/local/bin
5. ./ticker -w IBM

**Expected behavior**

Normally, ticker would just launch

**Screenshots**
If applicable, add screenshots to help explain your problem

 - OS: Linux Debian version: 11 (bullseye) 64bit
 - Terminal: LXterminal
 - Terminal Version:  0.4.0
 - Font: (Optional) Monospace 16
 - ticker Version: 4.5.14

**Additional context**

**Comment by herby-popnecker** [comment]
FYI. I am running the same version of ticker on the same O/S on a rPi 4 and it works well
--herbie-

**Comment by thaihugo** [comment]
This probably a bug with 16K pages. If you use the kernel=kernel8.img in the /boot/firmware/config.txt (the one that is actually used on the RPI4) it willl work because this is a 4K page kernel. I've tested this solution myself.

To the developer: This bug is related to the ability in newer kernels to work with 16K memory pages. It means that something in your components is probably not happy with this king of configuration. I hope it can shed some light on what's happening.

**Comment by achannarasappa** [comment]
Thanks for reporting the issue and the suggestion on the root cause. I'll take a look into fixing it in the next week or two

**Comment by herby-popnecker** [comment]
Thank you for taking the time to respond to this problem.Been using ticker for years on rPi. It's regrettable it no longer runs.
Do you know if i change the kernel page size in config.txt will result in any performance issues on the rPi5 ?
    On Thursday, May 30, 2024 at 04:31:02 AM CDT, thaihugo ***@***.***> wrote:  
 
 


This probably a bug with 16K pages. If you use the kernel=kernel8.img in the /boot/firmware/config.txt (the one that is actually used on the RPI4) it willl work because this is a 4K page kernel. I've tested this solution myself.

To the developer: This bug is related to the ability in newer kernels to work with 16K memory pages. It means that something in your components is probably not happy with this king of configuration. I hope it can shed some light on what's happening.

**Comment by thaihugo** [comment]
Officially, it would be around 10% performance lost approximately. But from my experience, you can't really fell the difference if you are not maxing a CPU with an heavyweight app or an emulation. For desktop work, you will probably forget the speed from 16k pages kernel after a few minutes. 

Le 2 juin 2024 11:47:21 UTC, herby-popnecker ***@***.***> a écrit :
> Thank you for taking the time to respond to this problem.Been using ticker for years on rPi. It's regrettable it no longer runs.
>Do you know if i change the kernel page size in config.txt will result in any performance issues on the rPi5 ?

**Comment by herby-popnecker** [comment]
Good to know.Appreciate the reply.Hopefully, the author will update the app.Sent from my iPadOn Jun 2, 2024, at 8:16 AM, thaihugo ***@***.***> wrote:﻿
Officially, it would be around 10% performance lost approximately. But from my experience, you can't really fell the difference if you are not maxing a CPU with an heavyweight app or an emulation. For desktop work, you will probably forget the speed from 16k pages kernel after a few minutes. 



Le 2 juin 2024 11:47:21 UTC, herby-popnecker ***@***.***> a écrit :

> Thank you for taking the time to respond to this problem.Been using ticker for years on rPi. It's regrettable it no longer runs.

>Do you know if i change the kernel page size in config.txt will result in any performance issues on the rPi5 ?

**Comment by achannarasappa** [comment]
I don't have access to a system to replicate confirm the fix / replicate this issue but I believe it is related to `upx` and [this issue](https://github.com/upx/upx/issues/254). I've upgraded the version of upx before building the latest release `v4.6.3` which _should_ fix the issue. When you have a moment, give the latest version a shot and let me know if it fixes the problem.

**Comment by thaihugo** [comment]
> I don't have access to a system to replicate confirm the fix / replicate this issue but I believe it is related to `upx` and [this issue](https://github.com/upx/upx/issues/254). I've upgraded the version of upx before building the latest release `v4.6.3` which _should_ fix the issue. When you have a moment, give the latest version a shot and let me know if it fixes the problem.

The new v4.6.3 indeed solves the problem. The build runs perfectly on a 16K page kernel. Thanks for solving this so fast!

**Comment by achannarasappa** [comment]
Glad to hear it fixed the issue!
