### ISSUE TITLE
Allow empty watchlist 

### ISSUE THREAD

**Issue by nborrmann** [achannarasappa/ticker#27]
First of all, this is awesome! I actually wanted to write something very similar myself but did not get around to doing it. Thank you!

Additionally, it would be nice to allow an empty watchlist.

**Comment by achannarasappa** [comment]
@nborrmann great to hear your finding it useful!

In regards to the empty watchlist, is the idea to allow for use cases where users want to only track symbols that they have positions in i.e. if `lots:` is set, `-w` flag and `watchlist:` in config are not required?

**Comment by nborrmann** [comment]
Yeah, exactly. If I leave the watchlist empty in the yaml, or remove the parameter from the yaml, it always complains about this.

**Comment by achannarasappa** [comment]
Fixed in latest release
