### ISSUE TITLE
ERROR RSTY from Yahoo API

### ISSUE THREAD

**Issue by sed11q** [achannarasappa/ticker#279]
**Describe the bug**
Attempts to invoke ticker generates the following error message:

2024/11/01 08:49:31.938297 ERROR RESTY yahoo session refresh error: unexpected response from Yahoo API: A3 session cookie missing from response, Attempt 2
yahoo session refresh error: unexpected response from Yahoo API: A3 session cookie missing from response

No changes in how I invoke ticker from my end.

OS: Ubuntu 24.04
Term: terminator
Term Version: 2.1.3
Ticker Version: 4.6.3

**Comment by achannarasappa** [comment]
It looks like it's still working okay for me in the US. Are you based in a country other than the US?

**Comment by sed11q** [comment]
US.

**Comment by sed11q** [comment]
Well, hate to admit it, but after desktop reboot the issue is no longer appearing. Should have tried terminal reboot first.

**Comment by achannarasappa** [comment]
Glad to hear you got it resolved!
