### ISSUE TITLE
Add a thousands separator

### ISSUE THREAD

**Issue by nborrmann** [achannarasappa/ticker#28]
Large position numbers would be easier to read with a thousands separator, or even better make the number format string configurable.

**Comment by achannarasappa** [comment]
@nborrmann thanks for the suggestion. Would you be able to provide some example use cases for number format configurability? (beyond commas)

**Comment by nborrmann** [comment]
Other countries use different numbers. Eg in germany the usage of commas and dots is reversed. Dots for thousands separators, commas for decimals (eg 1.000.000,00 for a million).

**Comment by samipenitaai** [comment]
Hi, I'm interested in learning how to code a trading bot, any direction of help would be awesome,🤙🏾🤙🏾🙏🏾ty
