### ISSUE TITLE
ticker --version returns 0.0.0

### ISSUE THREAD

**Issue by timsj** [achannarasappa/ticker#280]
**Describe the bug**
On latest ticker version 4.7.0, using the "ticker -v" or "ticker --version" command returns "ticker version v0.0.0"

**To Reproduce**
Use "ticker -v" or "ticker --version"

**Expected behavior**
The current version number should appear.

**Environment (please complete the following information):**
 - OS: Mac
 - Terminal: WezTerm
 - Terminal Version: 20240203
 - Font: JetBrains Mono
 - ticker Version: v4.7.0

**Comment by do-i** [comment]
The same issue appears in `ticker-4.7.0-linux-amd64.tar.gz` as well.

**Comment by achannarasappa** [comment]
Thanks for reporting this issue, I've pushed a fix in v4.7.1 that fixes this problem. Please reopen this issue if you still see it in the latest version
