### ISSUE TITLE
Missing characters for symbols and seperator lines.

### ISSUE THREAD

**Issue by josephreynolds1** [achannarasappa/ticker#29]
I am getting missing/placeholder characters when using the st terminal with the Terminus font.

Can you provide info on what fonts are necessary for showing the seperator and missing symbol characters.

![image](https://user-images.githubusercontent.com/46980014/106749025-08dc1a00-65f4-11eb-97ff-89995a18ba06.png)

**Comment by achannarasappa** [comment]
@josephreynolds1 I've added a note in the readme about the proper fonts to use since this seems to be a common question. This links has a full list of supported fonts: https://www.fileformat.info/info/unicode/char/23af/fontsupport.htm
