### ISSUE TITLE
Not all securities have a `PostMarketPrice`

### ISSUE THREAD

**Issue by favll** [achannarasappa/ticker#37]
`quote.go` uses `responseQuote.PostMarketPrice` if `responseQuote.MarketState == "POST"`, however, some securities do not have a post market price. E.g. the latest price for `https://query1.finance.yahoo.com/v7/finance/quote?lang=en-US&region=US&corsDomain=finance.yahoo.com&symbols=LUS.DE` after the market has closed will still be `RegularMarketPrice`. `ticker` wil therefore display `0.0` as latest price.

**Comment by achannarasappa** [comment]
Fixed in v3.0.7
