### ISSUE TITLE
Display the day growth during the off hours, too?

### ISSUE THREAD

**Issue by 097115** [achannarasappa/ticker#47]
If visiting a Yahoo page for a ticker during the off trade hours, you can still see the growth a stock had during the day compared to the previous close ([this blue rectangle](https://i.imgur.com/vyaElaT.png)).

In `ticker`, however, if no trade is going on, it's [equal to zeroes](https://i.imgur.com/xbJgpHc.png) :(

Would it be possible to fix this somehow? :)

**Comment by 097115** [comment]
Probably related: it seems that sometimes (and for some stocks) `ticker` can't obtain data from Yahoo: [example](https://i.imgur.com/FekWDum.png) (I have a position in $LLY, and yet it displays nothing -- while the other stocks are displayed just fine)

**Comment by achannarasappa** [comment]
Fixed with[de3e6ca690c057009e812a6d057d272c15d7c1f4](https://github.com/achannarasappa/ticker/commit/de3e6ca690c057009e812a6d057d272c15d7c1f4)
