### ISSUE TITLE
Add a changelog

### ISSUE THREAD

**Issue by nodesocket** [achannarasappa/ticker#48]
Can we get a `CHANGELOG.md` appended to when new versions are released?

**Comment by achannarasappa** [comment]
There's a changelog on the release page: https://github.com/achannarasappa/ticker/releases

Did you have something else in mind?

**Comment by nodesocket** [comment]
Thanks for this project. I did not see the changelog notes in GH releases. Typically this is maintained in a `CHANGELOG.md` file in the repo like:

https://github.com/nodesocket/jsonlite/blob/master/CHANGELOG.md

Then in the GH releases notes you can just say:

```
See CHANGELOG.md for details.
```

**Comment by achannarasappa** [comment]
Thanks for the suggestion however I think the changelog in releases is more maintainable since it's generated by the release tool automatically understanding the tradeoff being that some may expect a distinct changelog file which they won't find in the repo
