### ISSUE TITLE
Sorting?

### ISSUE THREAD

**Issue by 097115** [achannarasappa/ticker#5]
As for now, as I understand, it sorts tickers by their growth. This leads to tickers constantly changing their positions. Can sorting by name be implemented? 

Or, better, sort according to the order in the configuration file if one's present (this could allow custom sorting, visually separating a group of unrelated tickers, and also other things, like putting "lots" on top, and the rest of the watchlist below).

**Comment by achannarasappa** [comment]
This is a great suggestion - I'll have a look at adding this in the next couple of releases this week

**Comment by galmadar** [comment]
I suggest PR #21 for the requested enhancement.
Currently there is an option to sort by Symbol (name of the ticker) and by ChangePercent via the configuration file or a CLI argument.

**Comment by 097115** [comment]
@galmadar Great news! However, I'm probably missing something but it doesn't seem to work for me... :)

Pulled your fork/branch, built it, the sorting is indeed mentioned in the `--help` reference:

    --sort-quotes-by string   sort the quotes according to [Symbol, ChangePercent]. default sort is by ChangePercent (default "ChangePercent")

However, if running `./ticker -w UBER,AAPL --sort-quotes-by Symbol` stocks still seem not to be sorted alphabetically :)

![](https://i.imgur.com/BahcQWF.png)

**Comment by galmadar** [comment]
@097115 , Thank you for the comment!


The Bug happened because currently the quotes you mentioned (UBER, AAPL) are "inactive", and those quotes was concated **After** the orderBy method was called.

Anyway, I fixed that case, and when you will sort by `Symbol`, it will be sorted as expected.
Please pull and check it out again :)

**Comment by 097115** [comment]
@galmadar 

Thanks for bugfix!

However, as of commit a9b7422, something strange is still going on :)

1. `sort-quotes-by: "Symbol"` in `~/ticker.yaml` seems not to have any effect
2. the "easy" case `./ticker -w UBER,AAPL --sort-quotes-by Symbol` works fine. However, if we are reading stocks (both the wathchlist and the lots) from the config file, the results look a bit weird (just in case, in this example AAPL and LLY are the lots, others are from the watchlist):
2.1. [with `--sort-quotes-by`](https://i.imgur.com/wx84LNc.png)
2.2. [without `--sort-quotes-by`](https://i.imgur.com/YivS3G7.png)

**Comment by galmadar** [comment]
@097115 

1. My bad - the default was `ChangePercent` event when there is a value for the flag `sort-quotes-by` in the config file.
**Fixed that it in the last commit :)**
2. About this section - I'm not sure how you got this situation. I've tried A LOT of scenarios but I didn't got to this. I'll be glad if you provide another example for that case?

**Comment by 097115** [comment]
> Fixed that it in the last commit :)

It seems somehow this last commit 533015e fixed both issues :) Looks like the sorting by name works after all. Thanks for your efforts!

**Comment by galmadar** [comment]
@097115 
Thank you! :-)

@achannarasappa 
Please let me know if there is anything else missing before you can add it to the release

**Comment by for-coursera** [comment]
> Or, better, sort according to the order in the configuration file if one's present (this could allow custom sorting, visually separating a group of unrelated tickers, and also other things, like putting "lots" on top, and the rest of the watchlist below).

Wow, these user-defined groups would be so great!

**Comment by achannarasappa** [comment]
Great work @galmadar! The feature's been merged and is available in release [v2.3.0](https://github.com/achannarasappa/ticker/releases/tag/v2.3.0)
