### ISSUE TITLE
Summary mixes up currencies

### ISSUE THREAD

**Issue by mathiastj** [achannarasappa/ticker#51]
First off, thanks for a cool little utility.

The new summary feature `--show-summary` seems to add up all values without taking into account the currencies.

That is, they are all summed up even though the currencies are not the same, here is an example with a stock in USD and a crypto in EUR
<img width="1191" alt="Screenshot 2021-02-04 at 12 05 29" src="https://user-images.githubusercontent.com/2278040/106884317-7023c800-66e1-11eb-9663-0300b8a8e36c.png">

**Comment by dtcooper** [comment]
Also note cryptos aren't included in summary, ie `BTC-USD` and `BTC-DOGE`

**Comment by achannarasappa** [comment]
Fixed in release v3.1.0
