### ISSUE TITLE
Positioning of Update Datetime

### ISSUE THREAD

**Issue by valentin-ok** [achannarasappa/ticker#52]
The positioning of the update datetime in the lower right corner is cut off on two terminals I tested.
Is it possible to to align it with the current value (which isn't cut off).

Best Regards
![ticker_cutoff_date](https://user-images.githubusercontent.com/75795471/106886749-867f5300-66e4-11eb-975d-67c7d4028c95.png)

**Comment by achannarasappa** [comment]
@valentin-ok would you be able to provide information on the terminal and font you are using?

**Comment by valentin-ok** [comment]
Terminal: konsole 
Terminal Font: MesloLGS NF 9

but if it's just me you can close the issue. I have fixed this in my private fork inserting a space on the right side. I couldn't really pinpoint the issue and this was a dirty little hotfix for my own sanity.

**Comment by achannarasappa** [comment]
Thank for the info - I suspect it could be a font related problem since I haven't heard any other reports of this issue and I've tried on a few different combos of OS/terminal/fonts myself.

I'll close this issue for now but if you're able to pinpoint it to a code related problem let me know.
