### ISSUE TITLE
Interval is ignored

### ISSUE THREAD

**Issue by LtPinback** [achannarasappa/ticker#58]
As far as I can tell the interval flag and the corresponding option in the yaml configuration file is ignored thus always refreshing every 5 seconds.
Using Windows amd64 v2.2.0.

Also a version flag would be nice.

**Comment by madphilosopher** [comment]
Same issue on linux with v2.2.0 and this invocation:

`./ticker -i 60 -w BTC-USD,CAD=X,GME --show-separator `

**Comment by achannarasappa** [comment]
Fixed in v2.4.0
