### ISSUE TITLE
Auto-reload config file

### ISSUE THREAD

**Issue by Rudedog9d** [achannarasappa/ticker#63]
**Describe the solution you'd like**
Automatically reload the configuration file when it changes.

**Describe alternatives you've considered**
Using `inotifywait` or [`entr`](http://eradman.com/entrproject/).

**Additional context**
Using inotify on linux should be relatively easy?

**Comment by achannarasappa** [comment]
Thanks for the suggestion - would this require a code change in ticker itself? My understanding is that a tool like `entr` could hypothetical be used to reload `ticker` based on a config file change

**Comment by Rudedog9d** [comment]
I was having some issues getting it to work correctly with `entr`. I figured it would be a nice feature to have built in, and if it was built in, it would/could be cross platform (using something like https://github.com/fsnotify/fsnotify).

I glanced through the code, and I wasn't sure where the best place to implement a file watcher was. If you could suggest a location in the code, and are interested in the feature, I could look into implementing it.

**Comment by achannarasappa** [comment]
PRs are definitely welcome!

Currently the config file is read in at start time [here](https://github.com/achannarasappa/ticker/blob/master/cmd/root.go#L69)

If it's possible to trigger a reload on file change that would be the ideal way to implement this but I'd have to do a bit of research to give a more specific recommendation.

**Comment by travis-mark** [comment]
As an alternative to live reload, I was thinking about if $EDITOR (or similar) is defined, add a command "e: edit stocks" that opens .ticker.yaml from $EDITOR in a subprocess and then refreshes the list on close.

**Comment by Rudedog9d** [comment]
@travis-mark My use case is writing the file from an outside application. Opening an editor on exit would be pretty trivial with bash:

```bash
while true; do ./ticker --args; vi config.yml; done
```
