### ISSUE TITLE
Request to toggle on/off the display the my dollar balances.

### ISSUE THREAD

**Issue by reefland** [achannarasappa/ticker#65]
Would like the option to be able to toggle on/off the display the my dollar balances.

I'd like to be able to press a key such as `T` to toggle balance amount off, take a screen shot and toggle the balance back on.  Displaying all the gains / loss and percentages are fine.  I would just like a quick way to not show how much is actually invested.

In the yaml file, would like the ability to define if this feature is on or off by default at startup.

**Comment by cwarden** [comment]
I know @achannarasappa expressed some reservations about adding interactivity features, but I like this idea: b4e235bfa4d19b5d1e60834d52458dda219d208f
