### ISSUE TITLE
Bottom status bar covering information

### ISSUE THREAD

**Issue by kamiyaa** [achannarasappa/ticker#73]
**Describe the bug**

**To Reproduce**
1. Start ticker with `show-fundamentals: false` `show-tag: false`
2. Scroll to the very bottom

**Expected behavior**
What should happen: See the price of the last stock
What actually happens: Last stock price is covered by bottom bar

**Screenshots**
![2021-02-05_12-11_126560005_scrot](https://user-images.githubusercontent.com/8345320/107065662-04a62d00-67ab-11eb-84b9-88ad4068fbdd.png)

**Environment (please complete the following information):**
 - OS: Linux
 - Terminal: alacritty
 - Terminal Version: 0.6.0
 - ticker Version: b2eb1440e4c226287b5c4f2ac455841ae6cd6d4f

**Comment by achannarasappa** [comment]
Thanks for reporting this. This has been fixed and will be available in the next release
