### ISSUE TITLE
Docker support

### ISSUE THREAD

**Issue by junior** [achannarasappa/ticker#74]
**Proposed Solution**
Create Dockerfile and publish to Docker hub for easy usage without need to install the cli

**Use Cases**
Run Docker command to run Ticker

**Additional context**
Pull request already created with the solution. PR #75

**Comment by junior** [comment]
# Testing

Already published on Docker Hub: https://hub.docker.com/r/junior/ticker 

```shell
docker run -it --rm junior/ticker -w AAPL,TSLA,BTC-USD
```

## Using options

```shell
docker run -it --rm junior/ticker \
  --show-tags --show-fundamentals --show-separator \
  -w BTC-USD,AAPL,TSLA
```

## using configuration file

```shell
docker run -it --rm -v ${PWD}/.ticker.yaml:/.ticker.yaml junior/ticker
```

**Comment by achannarasappa** [comment]
Thank you for the suggestion and proposed solution!

I think the ideal implementation would have the the image built through goreleaser/Github Actions: https://goreleaser.com/customization/docker/

This would ensure the latest version is always available on Docker Hub

**Comment by junior** [comment]
> Thank you for the suggestion and proposed solution!
> 
> I think the ideal implementation would have the the image built through goreleaser/Github Actions: https://goreleaser.com/customization/docker/
> 
> This would ensure the latest version is always available on Docker Hub

Agree. Currently using the git docker integration, but would work better on the main repo.

An action would integrate better.

**Comment by achannarasappa** [comment]
I've added a Github Action to build and publish to Docker Hub. Have a look and see if it meets your need

**Comment by junior** [comment]
Looks great, but this implementation does not run on Docker running Apple Silicon or Docker on Raspberry Pi.

I've created another pull request, including this support.

Also included an option to include a new organization on docker, for easy remembering docker run command. You are owner of the organization. For your evaluation
