### ISSUE TITLE
XDG compliance

### ISSUE THREAD

**Issue by evamvid** [achannarasappa/ticker#8]
It would be great if by default check for the configuration file in XDG_CONFIG_HOME (this is `~/.config` for 90% of people), and maybe also XDG_CONFIG_HOME/ticker as well as in ~ for a configuration file, so as not to pollute the home directory with dotfiles.

Normally I'd have just submitted a pull request but I don't know Go, but I'm happy to help with any details or clarifications about it.

Cool project!

**Comment by achannarasappa** [comment]
Thanks for the suggestion! From your description, this makes total sense to include. I'll do a bit more research on XDG_CONFIG_HOME and look to include it in a release soon

**Comment by evamvid** [comment]
I went ahead and implemented it and sent you a Pull Request. #10

**Comment by achannarasappa** [comment]
Closed with #10
