### ISSUE TITLE
Start ticker with default ~/.ticker.yml

### ISSUE THREAD

**Issue by caalberts** [achannarasappa/ticker#80]
**Problem Statement**

As a user, I want to start ticker to monitor my watchlist and existing lots in the default config `~/.ticker.yml`

**Proposed Solution**

Running `ticker` without any options starts `ticker` using the default `~/.ticker.yml`.

This would tie in with well with [a command to add a lot](https://github.com/achannarasappa/ticker/issues/81).

Example usage:

```shell
ticker # starts a new ticker environment with fresh ~/.ticker.yml
# quit ticker

ticker lots add abnb --quantity 100 --unit-cost 147.00 # adds this lot to ~/.ticker.yml
ticker watch estc # add estc to watchlist

ticker # starts ticker with abnb lot and estc in the watchlist
```

**Comment by caalberts** [comment]
@achannarasappa What do you think of this? If you think that this is feasible, I can take a stab at a PR.

**Comment by achannarasappa** [comment]
Thanks for the suggestion @caalberts 

I put some thought into this when originally thinking about how users would start ticker. I like the idea of being able to run a single command and having it start the application however I struggled to find a "reasonable" default for what stocks to watch. The stocks that users watch would be highly personal to them and by creating a pre-populated default set of stocks to watch, the user would have to almost certainly have to manually edit their `.ticker.yaml` to watch the stocks they care about. I could also see it leading to unexpected behaviors where users find the defaults present when they attempt to watch an invalid symbol (e.g. `ticker -w NOTAREALSYMBOL` would display the defaults without their symbol present).

For this reason I feel a default `.ticker.yaml` should not be set on first run

**Comment by caalberts** [comment]
> however I struggled to find a "reasonable" default for what stocks to watch

@achannarasappa  Thanks for considering this. If this is the only concern, I think a sensible defaults can be indexes such as S&P500 or Dow. These would avoid creating bias towards certain tickers as well.
