### ISSUE TITLE
Ticker command to add lot

### ISSUE THREAD

**Issue by caalberts** [achannarasappa/ticker#81]
**Problem Statement**

As a user, I want to add a lot at any time from the command line without having to edit `~/.ticker.yml`

**Proposed Solution**

Running a command such as `ticker lots add abnb --quantity 100 --unit-cost 147.00` adds this to the lots in `~/.ticker.yml`

This would tie in with well with [a command to start ticker without any flag](https://github.com/achannarasappa/ticker/issues/80).

Example usage:

```shell
ticker lots add abnb --quantity 100 --unit-cost 147.00 # adds this lot to ~/.ticker.yml

ticker # starts ticker with abnb lot
```

**Comment by achannarasappa** [comment]
Thanks for this suggestion @caalberts 

My view on this one is that it won't save users a whole lot of trouble over editing the `.ticker.yaml` file directly.

If you're keen to edit yaml directly from your terminal, I'd suggest something like `yq`/`jq` which can [achieve assignments](https://stedolan.github.io/jq/manual/#Assignment) like you describe
