### ISSUE TITLE
Price Precision Config

### ISSUE THREAD

**Issue by enescakir** [achannarasappa/ticker#86]
Thanks for great tool.

Number of the digits after the decimal point isn't enough especially for cryptocurrencies. Currently, precision is set to 2 in `ticker/internal/ui/util/format.go  >> ConvertFloatToString(f float64) string` file. It's very small.  `precision` configuration might be great.

I thought to open a PR, but I couldn't find a way to access config value in `ConvertFloatToString`. I didn't want to add `precision` as parameter to lots of places such as `ConvertFloatToString`, `ValueText`, `watchlist.NewModel`, `watchlist.item` etc.

**Comment by achannarasappa** [comment]
I wonder if there is a sensible default that could be applied here.

If we were to expose an option to set precision globally, stocks with high and low value per unit may look odd e.g. (100000.00000 and 0.00013).

This issue warrants a solution but what the solution is is not yet clear to me.

**Comment by enescakir** [comment]
Maybe we can decide it for each stock automatically. Yahoo Finance shows max 4 digit after dot.
It might me something like that
```
       stock < 10       --->   precision: 4     i.e.: 0.4375, 1.5436
 10 <= stock < 100      --->   precision: 3     i.e.: 10.543
100 <= stock            --->   precision: 2     i.e.: 100.30, 49435.97

```
![image](https://user-images.githubusercontent.com/993199/107470792-03934800-6b7d-11eb-9868-ab0180570124.png)

![image](https://user-images.githubusercontent.com/993199/107470853-1c036280-6b7d-11eb-8794-1b7779592507.png)

![image](https://user-images.githubusercontent.com/993199/107470809-08f09280-6b7d-11eb-9160-9310f85a4ae2.png)

![image](https://user-images.githubusercontent.com/993199/107472131-730a3700-6b7f-11eb-8272-6965c62cce22.png)

**Comment by achannarasappa** [comment]
Your suggestion looks sensible to me. A PR would be very much welcome :)
