### ISSUE TITLE
Sort by configuration file

### ISSUE THREAD

**Issue by mjross** [achannarasappa/ticker#87]
In the terminal window where the ticker data is displayed, the stocks (and other financial instruments) are by default sorted by percentage change for the day – specifically, the stock with the highest increase for the day is at the top of the list, and the stock with the largest decline is at the bottom. This might be helpful for some users who want to quickly see the biggest gainers and losers of the day. But this means that the ordering keeps changing throughout the day, making it harder to keep an eye on just a few stocks of most interest at that time.

Two other sort options are: `alpha` to sort by ticker name, and `value` to sort by position value.  These are good, but none of the three give the user complete control over the sorting.

It would be wonderful to have another option, to sort by the order of the stocks listed in the configuration file (which is the option I would use most often), perhaps `--sort config`.

This is just a suggestion for an otherwise excellent and very useful program. Thank you for creating it!

**Comment by achannarasappa** [comment]
Thanks for the suggestion and detailed problem statement/use case

I've heard this from a few other users and agree this should be incorporated into a future release

**Comment by mjross** [comment]
That sounds excellent. Thanks for your consideration!

**Comment by achannarasappa** [comment]
Added in release v3.1.0
