### ISSUE TITLE
Currency support

### ISSUE THREAD

**Issue by pgrunm** [achannarasappa/ticker#9]
As mentioned in the issue #6 I'd like to ask for currency support.

My suggestion is to add this by just watching the exchange value between the Euro and USD. You can watch the Dollar just like a usual [quote](https://finance.yahoo.com/quote/EURUSD=X?p=EURUSD=X&.tsrc=fin-srch), maybe you can add this.

Unfortunately If I try this on the [Yahoo API](https://query1.finance.yahoo.com/v7/finance/quote?lang=en-GB&region=GB&corsDomain=finance.yahoo.com&symbols=EURUSD) it doesn't work.

**Comment by evamvid** [comment]
For forex tickers, the correct symbol is, for example for EUR/USD, EURUSD=X. 

So the correct link for Euros would be:
https://query1.finance.yahoo.com/v7/finance/quote?lang=en-GB&region=GB&corsDomain=finance.yahoo.com&symbols=EURUSD=X

And if you put EURUSD=X into the configuration file, it should work.

**Comment by achannarasappa** [comment]
@pgrunm can you clarify if the request to support converting the native currency of an exchange or to track forex?

**Comment by Milchdealer** [comment]
Converting the native (or dollar) currency to the local currency of the terminal user.

**Comment by WhyNotHugo** [comment]
I'd love to see this request too.

To clarify, I'd like to see the value of my stocks and crypto in EUR, _not_ see the exchange rate USD<>EUR itself.

**Comment by pgrunm** [comment]
> 
> 
> @pgrunm can you clarify if the request to support converting the native currency of an exchange or to track forex?

I can clarify this. I would like to see the the value of stocks in my native currency. For me it's Euro for example.

**Comment by achannarasappa** [comment]
Added in release v3.1.0

**Comment by WhyNotHugo** [comment]
Thanks!
