### ISSUE TITLE
Feature request: some kind of tab or page option

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#94]
Would it be possible to have tabs or pages or something similar to that so that you could better organize the stocks you are monitoring?

For example say you wanted to have 1 tab for stocks that you have holdings in, then a second tab for stocks that you are monitoring but have not invested in yet. Or if you wanted to create tabs based on the stock type for example Tech/Commodity/Industrial etc.

Some way to better organize would be great imo, if you watch a lot of stocks for different reasons having them all on the same screen can be a lot to look at.

**Comment by achannarasappa** [comment]
Closing this one so we can consolidate discussion into #99
