### ISSUE TITLE
Some markets display price of 0.00 after hours

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#95]
I noticed that some markets display a price of 0 after the markets close instead of showing the last traded price. It looks like this happens for smaller 'Other OTC' markets, not sure if this is an issue with the app or the API but I thought everything pulled from the Yahoo API had the most recent price. It stills show the daily increase/decrease % which is weird but not the actual stock price.

**Comment by achannarasappa** [comment]
Fixed with v3.0.7. Please reopen if the issue you describe persists
