### ISSUE TITLE
App times out after a certain period

### ISSUE THREAD

**Issue by viperperidot** [achannarasappa/ticker#98]
I noticed that if you leave the application running overnight, at some point it loses connection and when you check it the next day it will not have updated since the previous day. Not a big deal because you can just restart the application but some people may want to just have it open all the time with live data.

**Comment by achannarasappa** [comment]
Would you be able to provide a screenshot that include the updated time in the bottom right corner?

**Comment by viperperidot** [comment]
I realized that because I use a VPN and sometimes lose connection that maybe this is not an issue with ticker and just a connectivity issue.
